### ISSUE TITLE
Missing Screen Events

### ISSUE THREAD

**Issue by rstone4-chwy** [segmentio/analytics-swift#102]
**Describe the bug**
We're integrating Segment into our telemetry system. But we're seeing  calls to `.screen(title:category:properties)` not being processed and visible in the debugger. I've validated that the event is written to disk in `Storage.write<T: Codable>(_:value)` and that it is being retrieved in `SegmentDestination.flush()` and sent to the Segment servers, with a success result in the callback. Calls using `.screen(title:category)` succeed also and are successfully displayed in the debugger. I also validated that swapping in the old analytics library works to send the event and have it appear in the debugger. Because I can validate that the SDK is sending the event properly and receiving a successful result, I don't think it is an SDK problem per-se except that I can swap in the old framework and it works so if this isn't the correct place to report the issue I understand. I've tried replicating the issue in a separate project with a similar setup but it seems to work sending an identical event.

Validation Work Done:
- Validated that sending an identical event using the `track` method works
- Validated that sending the same event through the old ObjC framework works
- Validated that sending the same event without properties through the `.screen<P: Codable>(title:category:properties:)` works
- Validated that sending the same event without properties does not work
- Validated that changing from the iOS connection to the Swift connection yields the same result

**To Reproduce**
- Unable to reproduce in external project

**Expected behavior**
Event appears in debugger

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Library Version in use: 1.0.6
 - Platform being tested: iOS 15.0 Sim & iOS  15.1 iPhone 11 Pro
 - Integrations in use: None

**Additional context**
- Event is being processed on a background DispatchQueue
- Event is being processed in an external dynamic framework

**Comment by bsneed** [comment]
Hi @rstone4-chwy,

Looking into this now and I'm not able to reproduce what you're seeing.  It appears to be working fine best I can tell.  If you could share more specifics about how your calling it, some example code or something, it might be helpful.  Please see the attached screenshots for what I'm seeing here.

<img width="915" alt="Screen Shot 2022-01-05 at 11 25 42 AM" src="https://user-images.githubusercontent.com/235787/148276765-d1ce917a-a31b-4e08-a7e7-c2e5b1562fe5.png">
<img width="991" alt="Screen Shot 2022-01-05 at 11 26 13 AM" src="https://user-images.githubusercontent.com/235787/148276826-e8da2e75-14ac-4395-803c-ddc86ee9032c.png">
<img width="1179" alt="Screen Shot 2022-01-05 at 11 26 35 AM" src="https://user-images.githubusercontent.com/235787/148276894-df8e76bf-8cd0-4dcb-bc79-5d6ff2ea9bf4.png">

**Comment by rstone4-chwy** [comment]
Hi @bsneed,
Thanks for help on this. We swapped in the ObjC module to keep things moving and I've swapped the Swift version back in to check this. I'm no longer able to replicate the issue. It was one of those situations where everything pointed to me doing something wrong except that I could validate everything else appeared in the debugger except this very specific scenario. I was able to track the call all the way through the Segment SDK and see it sent successfully but it wasn't appearing. The issue can be closed and I'll keep an eye on our testing to make sure that we don't see any dropped events.

**Comment by bsneed** [comment]
@rstone4-chwy ah, I see.  One thing to know about the segment debugger is that it's just a sampling of events.  The higher the volume of events coming in, the more likely you'll not see certain things show up.  Glad you're sorted now, please reopen if you need any more assistance here.
