### ISSUE TITLE
macOS - Support for both x64 and M1 chipset

### ISSUE THREAD

**Issue by MajuMadhusudanan** [segmentio/analytics-swift#109]
I'm getting the following error when i add package and rebuild macOS apps. Our apps target both intel chipset as well as M1 apple silicon chipset.

/AppDelegate.swift:14:8: error: could not find module 'Segment' for target 'arm64-apple-macos'; found: x86_64, x86_64-apple-macos, at: ~/Documents/GitHub/********/Build/Products/Debug/Segment.swiftmodule
import Segment

Will you support both chipsets?

**Comment by bsneed** [comment]
The package builds from source.  It sounds like the module is not being found at all.  I'd check your build config as that's where the issue probably lies.  Please reopen if you need further assistance.

**Comment by MajuMadhusudanan** [comment]
I don't see any build config issue. because i have other frameworks added into the same project. Only analytics-swift throws processor architecture mismatch error.

I have added the package using the below link: https://github.com/segmentio/analytics-swift
<img width="761" alt="Screenshot 2022-01-18 at 11 17 17 AM" src="https://user-images.githubusercontent.com/23079368/149878213-ac49aa32-37e5-4fcf-b939-c8563f52c180.png">
.git


My macbook is intel based one and i want to debug the app in my macbook. Thats why i put active architecture(debug) as Yes.

**Comment by MajuMadhusudanan** [comment]
This issue still exists. Anyone else facing this issue ?

**Comment by bsneed** [comment]
I'm pretty sure it's something in your project.  I build/run on an M1 Mac all day long.  Maybe you can post the compiler output.
