### ISSUE TITLE
macOS - Support for both x64 and M1 chipset

### ISSUE THREAD

**Issue by MajuMadhusudanan** [segmentio/analytics-swift#110]
I don't see any build config issue. because i have other frameworks added into the same project. Only analytics-swift throws processor architecture mismatch error.

I have added the package using the below link: https://github.com/segmentio/analytics-swift
<img width="761" alt="Screenshot 2022-01-18 at 11 17 17 AM" src="https://user-images.githubusercontent.com/23079368/149878213-ac49aa32-37e5-4fcf-b939-c8563f52c180.png">
.git

My macbook is intel based one and i want to debug the app in my macbook. Thats why i put active architecture(debug) as Yes.

_Originally posted by @MajuMadhusudanan in https://github.com/segmentio/analytics-swift/issues/109#issuecomment-1015090494_

**Comment by bsneed** [comment]
It already supports both of these.  Your project's build active architecture should be set to no if you intend on running the binary elsewhere on a different platform.

**Comment by MajuMadhusudanan** [comment]
I'm getting the following error:

Could not find module 'Segment' for target 'arm64-apple-macos'; found: x86_64, x86_64-apple-macos, at: /Users/majumadhusudanan/Documents/GitHub/mac/DerivedData/desktop/Build/Products/Debug/Segment.swiftmodule
