### ISSUE TITLE
Feature Request: Build Facebook App Events Destination plugin

### ISSUE THREAD

**Issue by jfrodden** [segmentio/analytics-swift#113]
**Is your feature request related to a problem? Please describe.**
We're trying to migrate away from CocoaPods towards Swift Package Manager for our dependency management and the lack of SPM support of [FacebookAppEvents](https://github.com/segment-integrations/analytics-ios-integration-facebook-app-events) is blocking us from completing that goal.

**Describe the solution you'd like**
We'd like to migrate all of our dependency management to Swift Package Manager, including Segment FacebookAppEvents

**Describe alternatives you've considered**
Our only option is to continue using CocoaPods for all our Segment, Facebook, and GoogleAnalytics/Firebase needs because Segment FacebookAppEvents pulls all the others in via CocoaPods and trying to import them both via CocoaPods and SPM creates build issues.

**Comment by bsneed** [comment]
Thanks @jfrodden!

If I were to write this for you over the next couple of days, would you be able to test it?

**Comment by jfrodden** [comment]
a qualified yes: modulo any other issues we encounter with moving the other libraries over to SPM (since they all seem to need to move in lock-step), along with any issues we encounter moving to the new (still in beta) version of segment sdk

**Comment by bsneed** [comment]
Excellent, I'll take a stab at it and let you know when I've got something for you to try.

Thanks so much @jfrodden !

**Comment by bsneed** [comment]
@jfrodden please see changes in #118 and lemme know how they work for you!  Thanks so much!

**Comment by jfrodden** [comment]
> @jfrodden please see changes in #118 and lemme know how they work for you! Thanks so much!

I'm able to add this repo via SPM now, but we also rely on other Segment related libraries which trigger some sort of conflict with this version: 
- https://github.com/AppsFlyerSDK/segment-appsflyer-ios
-  https://github.com/segment-integrations/analytics-ios-integration-firebase

Any pointers on how to get all this functionality to co-exist via SPM would be greatly appreciated.

**Comment by bsneed** [comment]
Heya @jfrodden 

You can't mix analytics-swift and analytics-ios in the same codebase.  Has to be one or the other.  There's destination plugins for both of those in the analytics-swift repo under the /examples folder already.

**Comment by bsneed** [comment]
@jfrodden also of note, we're working on making some of these destinations shown in the examples folder actual supported components with their own repos and packages.  In the meantime, you should be able to copy the destinations you need from the examples folder to your own codebase.
