### ISSUE TITLE
Events passed to Segment through the library are not passed automatically to Amplitude

### ISSUE THREAD

**Issue by grzegorzkrukowski** [segmentio/analytics-swift#129]
**Describe the bug**
We lately switched from our own http client to this library to get batching support, but we noticed that all events that are going through this library are not sent to our Amplitude destination.

We are passing exactly the same properties and events as through our old library and we use exactly same setup, but the one that goes through analytics-swift are only visible in Segment and never lands on Amplitude.

Even weirded when we use Event Tester and send them manually - it all goes through correctly.

**To Reproduce**
1. Use latest 1.2.2 library
2. Send some events to Segment that has Amplitude set as destination
3. Check that events that are visible in Segment are never send to Amplitude automatically

**Expected behavior**
I would expect to have all events being forwarded to Amplitude

**Platform (please complete the following information):**
 - Library Version in use: 1.2.2
 - Platform being tested: macOS 
 - Integrations in use: Amplitude

**Additional context**
Making curl request with same content just works and events are forwarded properly to Amplitude.

**Comment by bsneed** [comment]
@grzegorzkrukowski Events aren't transferred instantly, they're queued up to reduce network traffic.  See flushCount, flushInterval in the configuration.  To manually flush events, call the `flush()` method.
