### ISSUE TITLE
Enable macOSLifecycleEvents

### ISSUE THREAD

**Issue by chrisrecalis** [segmentio/analytics-swift#133]
**Describe the bug**
`trackApplicationLifecycleEvents` has no impact when running under macOS. No life cycle events are tracked.

**To Reproduce**
1. Setup analytics in a macOS environment with `.trackApplicationLifecycleEvents(true)`
2. Inspect networking no life cycle events get tracked 

**Expected behavior**
Expected life cycle events Application Installed, Application Opened, etc...

**Platform (please complete the following information):**
 - Library Version in use: `1.2.3`
 - Platform being tested: macOS 12.3
 - Integrations in use:  Mixpanel

**Comment by bsneed** [comment]
@migs647 looking into this.

**Comment by migs647** [comment]
PR: https://github.com/segmentio/analytics-swift/pull/141
