### ISSUE TITLE
Network object is missing carrier information

### ISSUE THREAD

**Issue by 215eight** [segmentio/analytics-swift#137]
**Describe the bug**

In `analytics-swift` the network object does not include the `carrier` property whereas `analytics-ios` did. Below a comparison of both objects

`analytics-ios v4.1.3`
```
"library": {
      "name": "analytics-ios",
      "version": "4.1.3"
    },
    "locale": "en-US",
    "network": {
      "carrier": "T-Mobile",
      "cellular": true,
      "wifi": false
    }
```

`analytics-swift v1.2.0`
```
library": {
      "name": "analytics-swift",
      "version": "1.2.0"
    },
    "locale": "en-US",
    "network": {
      "bluetooth": false,
      "cellular": true,
      "wifi": false
    }
```

**To Reproduce**
1. Using the `analytics-swift` library log an event
2. The event metadata will not include the `carrier` property in the `network` object

**Expected behavior**
The `network` metadata should be consistent between `analytics-ios` and `analytics-swift` SDKs. This is seen as a regression issue after upgrading to the new package.

**Platform (please complete the following information):**
 - Library Version in use: v1.2.0
 - Platform being tested: iOS
 - Integrations in use: N/A

**Additional context**
N/A

**Comment by bsneed** [comment]
@215eight cellularServiceProvider was deprecated in iOS 12.  We made the decision to not include this information because of the format changes that would be required in switching over to serviceSubscriberCellularProviders.

**Comment by 215eight** [comment]
Thanks a lot for the background on the decision here. As a customer that is upgrading from the 'analytics-ios` to the `analytics-swift` library this is seen as a regression issue because the `carrier` information was used before and is now no longer present. Is there a workaround you can offer? 

Also, should I open a feature request to keep this in the roadmap in case it is also useful for other customers?

**Comment by bsneed** [comment]
@215eight No problem.  I can write a sample plugin that would live in your code to get this information in there and make it available to everyone via the /examples folder.  Should just take a few minutes.
