### ISSUE TITLE
Integrations object not populated in SDK 1.2.0

### ISSUE THREAD

**Issue by 215eight** [segmentio/analytics-swift#138]
**Describe the bug**
After migrating from `analytics-ios` v1.1.2 to v1.2.0, the integrations field did not contain any information. 
When this happens events are shown in the live debugger for a source but do not reach the source destinations.

**To Reproduce**
1.  Add an integration like AppsFlyer to the segment client.
2. On `v1.1.2 ` trigger a track event and notice how the integrations object has a list of integrations.
3. Update the SDK to `v.1.2.0`
4. Trigger the same event. <--- Issue here
6. The integrations object is empty

Event `v1.1.2` 
```
{
  "context": {
    "library": {
      "name": "analytics-swift",
      "version": "1.1.2"
    },
    "locale": "en-US",
    "network": {
      "bluetooth": false,
      "cellular": true,
      "wifi": false
    }
  },
  "event": "Application Foregrounded",
  "integrations": {
    "AppsFlyer": false,
    "Segment.io": false
  },
  "receivedAt": "2022-04-11T23:21:53.134Z",
  "sentAt": "2022-04-11T23:21:52.706Z",
  "timestamp": "2022-04-11T23:21:44.226Z",
  "type": "track",
}
```

Event `v1.2.0`
```
{
  "context": {
		"library": {
      "name": "analytics-swift",
      "version": "1.2.0"
    },
    "locale": "en-US",
    "network": {
      "bluetooth": false,
      "cellular": true,
      "wifi": false
    }
	},
  "event": "Application Foregrounded",
  "integrations": {},
  "receivedAt": "2022-04-11T23:20:33.204Z",
  "sentAt": "2022-04-11T23:20:32.773Z",
  "timestamp": "2022-04-11T23:20:32.281Z",
  "type": "track",
}
```

**Expected behavior**
The integrations object should remain the same after upgrading from `v1.1.X` to `v1.2.X`

**Platform (please complete the following information):**
 - Library Version in use: v.1.2.0
 - Platform being tested: iOS
 - Integrations in use: AppsFlyer

**Additional context**
This regression issue was introduced on `v1.2.0`.

**Comment by bsneed** [comment]
@215eight please update to 1.2.3.  Reopen if that doesn't solve the issue, but I suspect it will.

**Comment by bsneed** [comment]
The integrations object will not longer be populated.  It'll all be in a metadata field now.

**Comment by 215eight** [comment]
Thanks a lot for the response. It will very helpful to get a an example of the analytics event in json format showcasing the new location of the integrations object. In addition to this, is there any configuration that is needed on the SDK to get these values included in the event payload? 

Thanks in advance

**Comment by bsneed** [comment]
No problem!  Once you're on 1.2.3, you should see the metadata field being populated correctly.  It's not intended for customers to modify this directly.  If you can explain your use case I can guide you to a proper solution.

**Comment by 215eight** [comment]
I did the upgrade to 1.2.3 and the issue is not resolved. Below the event using the same app configuring the SDK the same way, just with a different SDK version. 

This is hoe the SDK is configured,  two plugins are added during initialization. I assume the integrations object will report information based on the integrations added. If you can share how the integration object is populated / what it depends on it will be appreciated. As you mentioned this is something not modified by the client it is automatically reported by the SDK, just wanted to make it clear the app isn't manipulating this directly. 

SDK Config 
```
       let analytics = Analytics(configuration: analyticsConfiguration)

       let brazePlugin = BrazeEventPlugin()
        analytics.add(plugin: brazePlugin)


        let appsFlyerPlugin = AppsFlyerDestinationPlugin()
        analytics.add(plugin: appsFlyerPlugin)
```

Event on SDK version `1.1.2` correctly populating the integrations object. 

```
{
  "anonymousId": "0F692723-2F82-46FD-BA00-C94CB016016C",
  "context": {
    "app": {
      "version": "2.30.1"
    },
    "library": {
      "name": "analytics-swift",
      "version": "1.1.2"
    },
  },
  "integrations": {
    "AppsFlyer: false,
    "Segment.io": false
  },
  "originalTimestamp": "2022-04-12T18:58:57.453Z",
  "receivedAt": "2022-04-12T18:59:03.163Z",
  "sentAt": "2022-04-12T18:59:02.819Z",
  "timestamp": "2022-04-12T18:58:57.797Z",
  "type": "identify",
}
```

Event on SDK version `1.2.3` incorrectly populating the integrations object, sending it empty. 

```
{
  "anonymousId": "F993121C-2E92-4686-ACC8-B3BC19A277DC",
  "context": {
		"app": {
      "version": "2.31.0"
    },
    "library": {
      "name": "analytics-swift",
      "version": "1.2.3"
    },
  },
  "integrations": {},
  "originalTimestamp": "2022-04-12T19:25:59.907Z",
  "receivedAt": "2022-04-12T19:26:11.348Z",
  "sentAt": "2022-04-12T19:26:11.154Z",
  "timestamp": "2022-04-12T19:26:00.101Z",
  "type": "identify",
}
```

**Comment by bsneed** [comment]
Don't get hung up on the contents of the integration object.  It's now unused so the change there isn't unexpected.  Those appear to be abbreviated event payloads.  Look for the __metadata field that is in there, what does that look like?  Have you checked your braze and AppsFlyer instances to see if events arrived?

**Comment by 215eight** [comment]
After updating to 1.2.X, no events where flowing to Braze or AppsFlyer
although the events are received in segment. Trying to find the root cause
between the different SDK and the integrations object seemed to be the
culprit.

There is certainly something new in the 1.2.X SDK that is breaking our
pipeline

Not sure how to get to the metadata of the event from the live debugger.
Would you be able to point me to the documentation?

**Comment by bsneed** [comment]
Let me dig here some more and see what could be happening.  Will reopen this while I do that.  From what I can tell your setup appears to be correct.  If you look in your local debugger in Xcode, open up SegmentDestination.swift, you can put a breakpoint on the `queueEvent` method in there and see the full raw payload contents.  The Segment online debugger where you're seeing events has stripped off __metadata by then.

**Comment by bsneed** [comment]
@215eight can you give this another try?  Support was able to reproduce this, and then it seemed to magically fix itself.  We believe there may have an issue on the back end that got fixed by another team.

**Comment by 215eight** [comment]
We will give it a try, thanks for following up on this.

Could you please provide more information on the root cause of the problem?

The team tries to ensure all functionality and pipelines are functional
before submitting a release to the App Store but once a client goes out
with the SDK in it, it is out of our control. The only way to fix it is by
pushing a hotfix which take days to be processed.

It is very important to us to have more context around this.  Segment  is
being integrated in a banking app and the team wants to reach a level of
engineering excellence that will peace of mind to our customers and stake
holders

**Comment by bsneed** [comment]
No problem!  Let me know how your testing goes.  Please reach out to support for the finer details as I don't have insights on all the various bits of infrastructure that could've caused this.
