### ISSUE TITLE
Repetitive logging from library

### ISSUE THREAD

**Issue by rollyceballos** [segmentio/analytics-swift#145]
**Describe the bug**
A clear and concise description of what the bug is.  My Xcode debug console is flooded by repetitive thread_policy_set logs

```
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
```

**To Reproduce**
1. Setup simple integration
```
        let configuration = Segment.Configuration(writeKey: apiKey)
            .trackApplicationLifecycleEvents(true)
            .flushAt(10)
                
        let analytics = Segment.Analytics(configuration: configuration)
        
        Self.analytics = analytics
``` 
2. Run the app 
3. See the logs

**Expected behavior**
Logs should not have repetitive and unneeded logs from library

**Screenshots**
```
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
thread_policy_set(1) returned 46
```

**Platform (please complete the following information):**
 - Library Version in use: 1.0.6 and 1.3.0
 - Platform being tested: iOS
 - Integrations in use: none

**Comment by bsneed** [comment]
That log is not from our library. In no place do we even set thread policy details. Most likely something in your app or another library.

**Comment by rollyceballos** [comment]
This only shows up when using the segment swift library. If I don't start/init (and even remove) Segment these repetitive logs disappear.

**Comment by bsneed** [comment]
https://developer.apple.com/forums/thread/699925

**Comment by rollyceballos** [comment]
Thank you @bsneed for that find.  Really appreciate it.  I've been searching for hints of discussions about this log flooding and this is the only link I get it being discussed appropriately.  So it is an Apple bug.

**Comment by bsneed** [comment]
@rollyceballos No problem!  Yeah it looks that way unfortunately. :(

Hopefully they fix it soon, I can imagine how annoying that must be.  As to why it shows up with Segment, and not without, could be that because we create some threads of our own, along with any in your app, and it throws it past some threshold to start logging that code..  Not sure of course, just a hypothesis.
