### ISSUE TITLE
Xcode says that i can not use this framework, how i could resolve it ?

### ISSUE THREAD

**Issue by dimapupena** [segmentio/analytics-swift#150]
i am trying to add segmentio/analytics-ios to my project and use it, but i have got an error that this framework can be compiled only for target 13+ but i have 11+ in my project, probably you could provide some workarounds or how i could use your framework in my case ?

when i am trying to import Segment, i get an error "Compiling for iOS 11.0, but module 'Segment' has a minimum deployment target of iOS 13.0:"

i can not just increase target because i need 11+ in my application

**Comment by bsneed** [comment]
Our minimum deployment target is iOS 13, yes.  Unfortunately, the best I can suggest is to make a fork and perform the modifications to support iOS 11.
