### ISSUE TITLE
Identify call doesn't appear in web debugger with certain userId value

### ISSUE THREAD

**Issue by nickjf89** [segmentio/analytics-swift#151]
**Describe the bug**
I am calling the `identify` method with a hashed copy of the user's email address. This never appears in the web debugger, but when I change the `userId` to something short, such as my first name or "test", it works without issue. Is there a character limit applied? The segment debugger doesn't show any signs of errors.

**To Reproduce**
1. Do `identify(userId: "ee1d83696ded26626ad9fd3f9ad4a28f207cab5a")`
2. Notice no debugging errors in Xcode, but web debugger doesn't receive event.3. 
3. Do `identify(userId: "test")`
4. Notice that the event appears in web debugger.
 
**Expected behavior**
The event should be sent to Segment, and shown in the web debugger.

**Platform (please complete the following information):**
 - Library Version in use: 1.3.1
 - Platform being tested: iOS
 - Integrations in use: Amplitude

**Comment by nickjf89** [comment]
I've since found that there seems to be a character limit applied, as passing `ee1d83696ded26626ad9fd3` (a shortened version of the original id) is sent correctly.

Can you advise if this is a bug or expected? For context, we have other teams identifying with strings this length, it only seems to be a problem on the iOS sdk.

**Comment by bsneed** [comment]
Looking at this today

**Comment by bsneed** [comment]
I'm not able to reproduce this.  See the image below.  I think you might not be seeing it because events in the debugger are only a sampling of events, not every event that's received.  Best to check your downstream destinations to see if it's arriving on that end.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/235787/184219272-64d7aa34-22ac-4fd4-9508-70f15e88a914.png">

**Comment by nickjf89** [comment]
These identify events are not filtering through to Amplitude. I can see other events coming through, but they are retaining the old identify value (the shortened version I identified with previously).

So at this point, if I use the longer (and correct) value, I never see this in Segment debugger (even though ever other value I pass to identify is shown there), and I never see it in Amplitude.

**Comment by nickjf89** [comment]
Please reopen this issue @bsneed
