### ISSUE TITLE
Request: Add `options` to all `analytics-swift` callsites

### ISSUE THREAD

**Issue by jhurray** [segmentio/analytics-swift#155]
**Is your feature request related to a problem? Please describe.**
I'm trying to migrate from `analytics-ios` to `analytics-swift` and the main issue I'm running into is migrating `options`.

We use `Protocols` + `Typewriter` for our project, so adding `options` values to `parameters` will break our schema. We're using options for supplementary, non-critical context, and it would be great to re-add that field for `analytics-swift`. We will not be able to migrate without it. 

To make things more difficult, it seems that newer versions of typewriter ONLY support `analytics-swift`

**Describe the solution you'd like**
Add a `options: [String: Any]? = nil` parameter for `track`, `group`, `screen`, and `identify`.

**Describe alternatives you've considered**
Adding options to parameters. This is painful because it requires updating a ton of `Protocol` schemas with information that will differ across clients & client versions.

**Additional context**
If theres a reason why `options` are no longer supported we would love to understand it. In general `options` seem to be missing from your entire [migration guide](https://segment.com/docs/connections/sources/catalog/libraries/mobile/swift-ios/migration/) so some guidance / reasoning would be appreciated.

**Comment by bsneed** [comment]
@jhurray can you provide an example of what you're passing in via the options param on analytics-ios?  We purposefully removed that because it was being used as a workaround for a handful of things on analytics-ios and we didn't want to perpetuate it.  If you can show me an example of how you're using it, I can give you a path forward.
