### ISSUE TITLE
Doesn't build clean on Xcode 14 because of type 'Any' is not optional

### ISSUE THREAD

**Issue by jasonbobier** [segmentio/analytics-swift#157]
**Describe the bug**
analytics-swift/Sources/Segment/Utilities/JSON.swift:54:14 | type 'Any' is not optional, value can never be nil; this is an error in Swift 6 

**To Reproduce**
Build package on Xcode 14.

**Expected behavior**
Should build clean with no warnings

**Comment by bsneed** [comment]
Fixed with #161
