### ISSUE TITLE
trackPushNotifications missing from SDK

### ISSUE THREAD

**Issue by LarrrrryT** [segmentio/analytics-swift#158]
**Describe the bug**
Based on the Segment Documentation for the SDK there should be a function to enable automatic tracking for push notifications opens.  This isn't available on on the latest version 1.3.1.  Is this rolled up into deep links perhaps?

https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#api-call-queueing-in-analytics-ios

<img width="734" alt="Screen Shot 2022-09-29 at 11 08 25 AM" src="https://user-images.githubusercontent.com/3093650/193110090-2ff27007-30de-4182-8e2e-82b55980cdde.png">

**To Reproduce**
Try adding .trackPushNotifications to the `Configuration` class

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - 1.3.1
 - iOS

**Additional context**

**Comment by bsneed** [comment]
An example plugin for this is in progress by @alanjcharles

**Comment by alanjcharles** [comment]
Hi @LarrrrryT we decided against including this as a config option in the SDK and instead made a more agnostic example plugin, [found here](https://github.com/segmentio/analytics-swift/blob/main/Examples/other_plugins/NotificationTracking.swift). Please feel free to copy and/or alter it to suit your needs!
