### ISSUE TITLE
Zombie Analytics after deallocation.

### ISSUE THREAD

**Issue by frangrolemund** [segmentio/analytics-swift#159]
**Describe the bug**
Creating and deallocating the Analytics instances doesn't stop them from sending events to the back-end sources. 

**To Reproduce**
1. Allocate Analytics instance (1) with support for lifecycle events and connected to the Segment source.
2. Background the app and watch for application lifecycle event to appear in Segment debugger.
3. Deallocate analytics instance (1) and allocate Analytics instance (2) with support for lifecycle events and connected to the same Segment source.
4. Background the app and watch for duplicate application lifecycle events to appear in Segment debugger.
5. Goto 3. for more fun and more events!

**Expected behavior**
The Analytics instance should clean up after itself and shutdown its plugins when deallocated.   To be clear, I'm not expecting two valid instances to coordinate in any way - that would reasonably produce duplicates, but if there is only one app-wide, live instance that hasn't been released, it should be the _only_ one sending events.

**Screenshots**
<img width="716" alt="image" src="https://user-images.githubusercontent.com/11785548/193413104-9b679db7-2126-4c8c-bb5e-2a3220ef6c81.png">

**Platform (please complete the following information):**
 - iOS library version 1.3.0

**Additional context**
My use case requires my app be able to reconfigure Segment between logins so that I can attach to QA and production depending on the user's preference.

**Comment by malhotrachetan** [comment]
Any updates on this?

**Comment by frangrolemund** [comment]
> Any updates on this?

If it matters, it is possible to work around this issue by explicitly de-initializing elements of the segment client using their public APIs for the internal objects.  Although that allowed me to make progress, I'd expect any commercial library to clean up after itself correctly which is why I opened this issue.  That feels like a reasonable prerequisite.

**Comment by bsneed** [comment]
It's on my short to-do list.  Looking at some of these storage issues currently and will circle back soon.

**Comment by bsneed** [comment]
Fixed in #164
