### ISSUE TITLE
[Segment ERROR - finish(file:):320] Unable to rename to temp warning/error

### ISSUE THREAD

**Issue by malhotrachetan** [segmentio/analytics-swift#162]
**Describe the bug**

Coming across a very weird debug message lately since the last update. The message appears around 20 secs post starting the app. The message says:

`[Segment ERROR - finish(file:):320]
Unable to rename to temp: file:///Users/chetanmalhotra/Library/Developer/CoreSimulator/Devices/094C9BEE-0AB5-4345-AB1D-2CA907B66033/data/Containers/Data/Application/1688B1EE-1CCC-44B7-AA72-FB7A9A272B3E/Documents/segment/XVFH4DGT0ufXKfxlMQzNMQDosdD9eKLW/7-segment-events, Error: Error Domain=NSCocoaErrorDomain Code=4 "“7-segment-events” couldn’t be moved to “XVFH4DGT0ufXKfxlMQzNMQDosdD9eKLW” because either the former doesn’t exist, or the folder containing the latter doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/chetanmalhotra/Library/Developer/CoreSimulator/Devices/094C9BEE-0AB5-4345-AB1D-2CA907B66033/data/Containers/Data/Application/1688B1EE-1CCC-44B7-AA72-FB7A9A272B3E/Documents/segment/XVFH4DGT0ufXKfxlMQzNMQDosdD9eKLW/7-segment-events, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/chetanmalhotra/Library/Developer/CoreSimulator/Devices/094C9BEE-0AB5-4345-AB1D-2CA907B66033/data/Containers/Data/Application/1688B1EE-1CCC-44B7-AA72-FB7A9A272B3E/Documents/segment/XVFH4DGT0ufXKfxlMQzNMQDosdD9eKLW/7-segment-events.temp, NSFilePath=/Users/chetanmalhotra/Library/Developer/CoreSimulator/Devices/094C9BEE-0AB5-4345-AB1D-2CA907B66033/data/Containers/Data/Application/1688B1EE-1CCC-44B7-AA72-FB7A9A272B3E/Documents/segment/XVFH4DGT0ufXKfxlMQzNMQDosdD9eKLW/7-segment-events, NSUnderlyingError=0x600001e34e40 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

**To Reproduce**
1. Just run any project that uses identify() and track()
2. Wait for ~20 secs
3. See error

**Expected behavior**
There should be no warnings/werrors

**Screenshots**
<img width="936" alt="Screenshot 2022-10-15 at 2 54 57 AM" src="https://user-images.githubusercontent.com/13315992/195946415-2a26491d-64d5-4ed6-93aa-72e7ad2efea7.png">

**Platform (please complete the following information):**
 - Library Version in use: 1.3.1
 - Platform being tested: Ios 15
 - Integrations in use: Firebase and Amplitude

**Additional context**
Kinda urgent. Pls help saviours

**Comment by malhotrachetan** [comment]
Updated to 1.3.2, still happening.

**Comment by bsneed** [comment]
looking ...

**Comment by bsneed** [comment]
I'm unable to reproduce this.  I'm using the example app located in analytics-swift/examples/apps/BasicExample.xcworkspace.  From the looks of it, it seems to be failing to create the directory for the given writekey.  Line 196 in Storage.swift.  Can you see what the results of that are on your end?

**Comment by bsneed** [comment]
You might try the branch above and see if that helps any.

**Comment by malhotrachetan** [comment]
Hey! Just tried out with the above mentioned branch. Now i am getting:
<img width="934" alt="Screenshot 2022-10-16 at 11 46 56 PM" src="https://user-images.githubusercontent.com/13315992/196051432-1465b2e6-4781-4b76-bc8a-b5f7f8de13e3.png">

**Comment by bsneed** [comment]
Can you verify if those files or folders exist and those error messages are legit?

**Comment by malhotrachetan** [comment]
Yes the directory with writeKey name does infact exist, thus the file name "14-segment-events" or is missing.

**Comment by bsneed** [comment]
I didn't quite understand that last part.

You should have a 14-segment-events or a 14-segment-events.temp.

**Comment by malhotrachetan** [comment]
I meant there is a directory created with the writeKey name but neither 14-segment-events nor 14-segment-events.temp is created.

**Comment by bsneed** [comment]
Are you able to create and write to files manually in that directory?

**Comment by malhotrachetan** [comment]
Good point. Let me check this.

**Comment by malhotrachetan** [comment]
hey! As you feared, no I cannot create manually too. Got this:

`mkdir: /20-segment-events: Read-only file system`

**Comment by bsneed** [comment]
Ok, gotcha.  So it's all explained now.  I'm not sure why you have a read-only file system.  Do you know?

**Comment by malhotrachetan** [comment]
Idk. Apple ships it like this maybe? Anyway, so I got around making the root volume writable. Now i can make a directory/file manually in the writeKey named folder but I still get the message.

**Comment by bsneed** [comment]
Apple doesn't ship a readonly file system (not intentionally anyway).  Closing this as I've merged the PR and it should be good.  Please let me know if you see issues.  I need lots of details about what you're seeing etc to further assist.
