### ISSUE TITLE
CocoaPod installation supprot

### ISSUE THREAD

**Issue by nekto-zum** [segmentio/analytics-swift#166]
Hi! Do you plan to add CocoaPods support for this library as it is done for the Objective-C one? Or down the road Swift Package Manager will be the only supported one?

Asking mostly to understand if I should go through the hassle of integrating with source codes or wait for pods support.

Thanks!

**Comment by bsneed** [comment]
Hi @nekto-zum,

We won't be adding Cocoapods support.  They're too slow in supporting platform changes, etc.  It'll be SPM only from here on out.  The previous libs will deprecated soon.  Let me know if there's anything I (or we) can help with as you move through things.

**Comment by nekto-zum** [comment]
Thanks for a quick reply!

**Comment by bsneed** [comment]
No problem!!
