### ISSUE TITLE
No way to reset user id

### ISSUE THREAD

**Issue by nekto-zum** [segmentio/analytics-swift#169]
**Describe the bug**
There is a way to set user id and traits but there is no way to reset it (for example, if user logs out). It seems it is just a typo in the method definition as method description actually allows that:

```
/// Associate a user with their unique ID and record traits about them.
/// - Parameters:
///   - userId: A database ID (or email address) for this user. If you don't have a userId
///     but want to record traits, you should pass nil. For more information on how we
///     generate the UUID and Apple's policies on IDs, see https://segment.io/libraries/ios#ids
///   - traits: A dictionary of traits you know about the user. Things like: email, name, plan, etc.
public func identify<T: Codable>(userId: String, traits: T?) {
```

**Comment by alanjcharles** [comment]
Hi @nekto-zum you can reset a userId with the `reset()`  method: https://github.com/segmentio/analytics-swift/blob/main/Sources/Segment/Analytics.swift#L166

**Comment by bsneed** [comment]
@alanjcharles can you update the documentation he cited?  It's a bit confusing.

**Comment by nekto-zum** [comment]
I would actually argue that the `reset()` option you are proposing is a bit too nuclear for a general usage. Imagine you have login/logout events. I don't necessary want to reset _everything_, I want just to drop user id. Can more granular setting be added? As I mentioned in the referenced code it is actually supported to pass nil...

**Comment by bsneed** [comment]
While I can understand your point of view, the intent here is to preserve privacy of the user(s).  By resetting the anonymousId/user/etc via reset() there's nothing to link it back to a previous session. Our other libraries work this way and previous libs have worked this way for quite some time.  So calling `reset()` is the recommended path for what you're attempting to do.
