### ISSUE TITLE
Analytics class is not singleton

### ISSUE THREAD

**Issue by benMohamed** [segmentio/analytics-swift#187]
Hello,
Analytics class is not singleton, so Do I need to create a new one with new configuration each time I want to track an event, or manage a custom singleton in my project ?

**Comment by bsneed** [comment]
Hi @benMohamed,

You'd create/manage your own singleton.  You can see some patterns for this [here](https://github.com/segmentio/analytics-swift/blob/main/Examples/tasks/MultiInstance.swift) and [here](https://github.com/segmentio/analytics-swift/blob/main/Examples/apps/BasicExample/BasicExample/AppDelegate.swift).
