### ISSUE TITLE
ObjCExample not working

### ISSUE THREAD

**Issue by benMohamed** [segmentio/analytics-swift#189]
**Describe the bug**
"I tried your ObjCExample, but events are not being sent. I inserted breakpoints and observed that the event file is not being generated.

**To Reproduce**
Just launch your ObjCExample

**Comment by bsneed** [comment]
Can you provide some more detail?  That's not a whole lot to go on.

**Comment by benMohamed** [comment]
When integrating the SDK within Objective-C code, events are not received on the web platform. You can verify this with your ObjcExample. I set breakpoints in the code and discovered that the startBatchUpload function is not being executed and the events file is not being generated.

**Comment by bsneed** [comment]
Were you using your own write key?  What were your configuration options or were they the defaults?  Is your source set up on segment.com?  Whatever else you can think of that might be useful.

**Comment by benMohamed** [comment]
1 - **Were you using your own write key?** ==> Yes, and it functions correctly in the BasicExample https://github.com/segmentio/analytics-swift/tree/main/Examples/apps/BasicExample
2 - **What were your configuration options or were they the defaults?** ==> defaults one, as I said, I have just launched the ObjCExample, https://github.com/segmentio/analytics-swift/tree/main/Examples/apps/ObjCExample
3 - Does your ObjCExample work correctly? (on a Xcode 14.2)

**Comment by benMohamed** [comment]
I found that the code inside this queue : "let syncQueue = DispatchQueue(label: "sync.segment.com")" is never called!

**Comment by benMohamed** [comment]
Any help on this ?

**Comment by benMohamed** [comment]
in `public class StartupQueue`, why you made analytics var as weak 
`public weak var analytics: Analytics? = nil` ?

**Comment by bsneed** [comment]
Just dove into this.  Looks like there's an issue where something isn't set up quite yet on the objc side.  Will dive deeper and get a fix in place.

**Comment by benMohamed** [comment]
if you remove `weak` from this line `public weak var analytics: Analytics? = nil` in `class StartupQueue`, everything works fine

**Comment by bsneed** [comment]
Having it weak prevents a retain loop, which is why removing it makes it work.  In looking, it's actually a very simple mistake.  When the analytics instance is created, it's in the context of the method, and when it goes out of scope at the end, all the async processes it had in flight are cancelled.  I'll update the sample, but that should get you going for now.
