### ISSUE TITLE
Crashed: io.segment.analytics.segmentio

### ISSUE THREAD

**Issue by jueyi1989** [segmentio/analytics-swift#190]
Crashed: io.segment.analytics.segmentio
0  libobjc.A.dylib                0x3554 objc_release_x0 + 16
1  libobjc.A.dylib                0x3554 objc_release + 16
2  CoreFoundation                 0x29fcc cow_cleanup + 168
3  CoreFoundation                 0xb2bf0 -[__NSFrozenDictionaryM dealloc] + 124
4  CoreFoundation                 0x29fcc cow_cleanup + 168
5  CoreFoundation                 0xb2bf0 -[__NSFrozenDictionaryM dealloc] + 124
6  CoreFoundation                 0x29fcc cow_cleanup + 168
7  CoreFoundation                 0xb2bf0 -[__NSFrozenDictionaryM dealloc] + 124
8  CoreFoundation                 0x3055c -[__NSArrayI dealloc] + 80
9  Segment                        0xceb0 __destroy_helper_block_e8_32s40s + 24
10 libsystem_blocks.dylib         0x2124 _call_dispose_helpers_excp + 48
11 libsystem_blocks.dylib         0x1d54 _Block_release + 252
12 libsystem_blocks.dylib         0x2124 _call_dispose_helpers_excp + 48
13 libsystem_blocks.dylib         0x1d54 _Block_release + 252
14 libdispatch.dylib              0x3fdc _dispatch_client_callout + 20
15 libdispatch.dylib              0xb694 _dispatch_lane_serial_drain + 672
16 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke + 384
17 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread + 652
18 libsystem_pthread.dylib        0xdf8 _pthread_wqthread + 288
19 libsystem_pthread.dylib        0xb98 start_wqthread + 8

**Comment by bsneed** [comment]
There's not really enough info here for me to look into this.  Can you add a more complete trace or scenario which caused it, or anything?
