### ISSUE TITLE
Strange behaviour when SDK does batch request

### ISSUE THREAD

**Issue by 01dr** [segmentio/analytics-swift#191]
**Describe the bug**
SDK sends /b requests with strange payload. It looks like the first part of JSON missed. It starts from comma
```
    ,
    { Event },
    { Event },
    { Event },
  ],
  "sentAt": "2023-02-03T15:06:17.815Z",
  "writeKey": "writeKey"
}
```

**Expected behavior**
SDK sends valid JSON
```
{
  "batch": [
    { Event },
    { Event },
    { Event },
    { Event },
  ],
  "sentAt": "2023-02-03T15:06:17.815Z",
  "writeKey": "writeKey"
}
```

**Platform (please complete the following information):**
 - Library Version in use: 1.3.1
 - Platform being tested: iOS/Swift SDK

**Comment by bsneed** [comment]
Update to 1.3.5.  Another user reported this and submitted a PR, should be fixed.
