### ISSUE TITLE
Segment: Module not found error | Only for iOS simulator

### ISSUE THREAD

**Issue by sree127** [segmentio/analytics-swift#195]
**Describe the bug**
After following the steps as mentioned here -> https://segment.com/docs/connections/sources/catalog/libraries/mobile/swift-ios/
 
But I'm getting the following error when trying to build for the simulator, running on M1 machine
```
/Users/XXX/XXX/mobile-ios/XXX/NextLogbook/XXX/Services/AnalyticsApplicationService.swift:9:8: Could not find module 
'Segment' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: 

/Users/XXX/Library/Developer/Xcode/DerivedData/XXX-egrhpjpqbjdovzbfulrmhhblsube/
Build/Products/Debug-iphonesimulator/Segment.swiftmodule
```

And this is how the Build Settings are:
**1. Project settings**
<img width="730" alt="Screenshot 2023-02-27 at 17 01 13" src="https://user-images.githubusercontent.com/3157263/221614799-2e55217e-afe4-4ac7-8e61-2743dc1d2c7d.png">

**2. Target settings**
<img width="736" alt="Screenshot 2023-02-27 at 17 01 01" src="https://user-images.githubusercontent.com/3157263/221614837-1fcc0284-72e2-4211-ab13-01878a56aee7.png">

**Package dependencies**
<img width="369" alt="Screenshot 2023-02-27 at 17 03 51" src="https://user-images.githubusercontent.com/3157263/221615344-78f14648-8883-476e-ba03-9b5f7d6a5f7d.png">

**Expected behavior**
Be able to build to compile and build successfully. The same config works well on a real device.

**Platform (please complete the following information):**
 - Library Version in use: 1.3.5
 - Platform being tested: iOS 16.1 Simulator

**Comment by bsneed** [comment]
Sometimes I've seen certain unconventional setups (like using a local package) where the addition of the library being linked gets missed by Xcode.  Can you look and see if it's being linked for the debug build?

**Comment by bsneed** [comment]
You might also try a test project to see what differences might be between your project and the streamlined basic one.  Typically I just add the dependency and everything is good to go.  I'm relatively certain it's something about the setup you have there that I can't see.
