### ISSUE TITLE
Support Swift's `Set` as a JSON type

### ISSUE THREAD

**Issue by jnpdx** [segmentio/analytics-swift#198]
**Is your feature request related to a problem? Please describe.**
`track(name: String, properties: [String: Any]? = nil)` will crash if one of the `Any` is a Swift `Set`. It will _not_ crash if that same property is an `Array`.

**Describe the solution you'd like**
Because to JSON, `Array` and `Set` are identical, it would be nice if Segment's `JSON` type could encode `Set` without crashing

**Describe alternatives you've considered**
At this point, we just ensure we're always sending an `Array`

**Additional context**
N/A

**Comment by rtharston** [comment]
It might be nice to support all types of `Collection` or maybe `Sequence` and treat them all like `Array`.

**Comment by bsneed** [comment]
Thanks @jnpdx & @rtharston!  I'll have a look at this and get back to you guys shortly.

**Comment by bsneed** [comment]
I handled `Set` explicitly.  I didn't see a good way to handle types like Collection or Sequence easily.  If you guys have a suggestion, lemme know.  Otherwise we'll roll with this.

**Comment by rtharston** [comment]
> I handled `Set` explicitly. I didn't see a good way to handle types like Collection or Sequence easily. If you guys have a suggestion, lemme know. Otherwise we'll roll with this.

That's great! Thanks! The Collection and Sequence idea was just if it was simple. Set is the common one. 😄

**Comment by jnpdx** [comment]
Thanks so much!

**Comment by bsneed** [comment]
No problem!  Thank you guys for the report!
