### ISSUE TITLE
WriteKey is not passed as an Authorization header

### ISSUE THREAD

**Issue by dannys42** [segmentio/analytics-swift#203]
**Describe the bug**
It does not appear the WriteKey is included as an Authorization Header.  `configuredRequest()` makes no mention of "Authorization".  And there appears to be an internal function named `authorizationHeaderForWriteKey()` that is not referenced.  `configuredSession()` and `startBatchUpload()` also take in the `writeKey` as a parameter but never makes use of it.

**To Reproduce**
We especially noticed this error because we're using `requestFactory()` to send data through our own proxy URL.  It was our understanding that the `Authorization` header was required.

**Expected behavior**
`Authorization` header should be sent in batch uploads.

**Platform (please complete the following information):**
 - Library Version in use: 1.3.5
 - Platform being tested: iOS
 - Integrations in use: n/a

**Additional context**
Segment [API documentation](https://docs.segmentapis.com/tag/Authentication) clearly indicates `Authorization` header is a requirement.

**Comment by dannys42** [comment]
I also noticed that the API sends the writeKey in the query path of the settings API.  Is this safe?

**Comment by bsneed** [comment]
Hi @dannys42!  The way as documented in the API does still work.  However, we've begun moving everything away from that on the mobile libraries side.  While writekey was never guaranteed to be private in any way, we've started to modify systems to tighten this up.  There's a little cleanup still needed there, but writekey is no longer sent in the URL or in the auth header and instead the JSON payload contains the writekey information necessary.

**Comment by samarti** [comment]
Hi @bsneed. Could you please elaborate on how to pass the Authorization header? We're working with v1.4.1 as part of a migration from Analytics iOS, but can't set the header.
