### ISSUE TITLE
Support async for Plugins

### ISSUE THREAD

**Issue by dannys42** [segmentio/analytics-swift#205]
**Is your feature request related to a problem? Please describe.**

We'd like to use the `EventPlugin` to be able to capture UI related states.  However in the up-coming Swift 6 concurrency model, much of the APIs are MainActor isolated. (i.e. set Swift Concurrency Checking = Complete).  This makes it hard to reliable capture these states in events.

**Describe the solution you'd like**

Specifically, it would be nice if the functions defined in `EventPlugin` were defined as `async`.  This would make it easier for plugins as they can then simply await the value.

**Describe alternatives you've considered**
Most alternatives rely on either pre-caching the data or making use of semaphores.  Both methods can be fragile, resulting in either attributes that are not accurate, complications in initialization, or potential code dead-lock.

**Additional context**

**Comment by bsneed** [comment]
Hi @dannys42,

I'm not quite sure I understand your usage.  The methods on EventPlugin shouldn't be getting called directly, but rather indirectly via analytics.track etc.  Can you elaborate?

**Comment by bsneed** [comment]
Hi @dannys42, closing this to clear out the board.  Please reopen if you have more info and an example use case.  Thanks!
