### ISSUE TITLE
UIKitScreenTracking class missing

### ISSUE THREAD

**Issue by xmollv** [segmentio/analytics-swift#206]
I've migrated Segment from Cocoapods to SPM, and I had to go though the migration. Everything seems fine except for the automatic view tracking. [In the docs](https://segment.com/docs/connections/sources/catalog/libraries/mobile/swift-ios/#screen), there's an example on how to set it up:

```swift
 analytics.add(plugin: UIKitScreenTracking())
```

but that doesn't seem to compile because it can't find it.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/8229382/226573624-0667a0e4-9805-45db-ad91-a333c2573333.png">

It's not able to find the `UIKitScreenTracking` class. Are we supposed to copy & paste the class in our own source instead of using it directly from the SPM package?

**Comment by bsneed** [comment]
That file is in the /examples/other_plugins folder.

**Comment by xmollv** [comment]
> That file is in the /examples/other_plugins folder.

I know it's there. That's why I asked the following question: 

> Are we supposed to copy & paste the class in our own source instead of using it directly from the SPM package?

Could you please confirm if we're supposed to be able to access `UIKitScreenTracking` without copying it manually to our source code? Or the default way is to copy the file into our own repository?

**Comment by bsneed** [comment]
@xmollv ah yeah, sorry.  I missed that part.  Yes, the intent is to copy/modify as necessary.  We've found customers typically want to customize this aspect of tracking pretty regularly.

**Comment by xmollv** [comment]
> @xmollv ah yeah, sorry. I missed that part. Yes, the intent is to copy/modify as necessary. We've found customers typically want to customize this aspect of tracking pretty regularly.

Got it, thank you.

**Comment by ACPK** [comment]
@xmollv @bsneed Thanks for the comments above! Where did you copy/paste the code? 

I created a file "UIKitScreenTracking.swift" and uses the code `analytics.add(plugin: UIKitScreenTracking())` from the [Segment.io Swift Docs](https://segment.com/docs/connections/sources/catalog/libraries/mobile/swift-ios/#screen).

However, line #15 causes the error below.

    import UIKit
    import Segment

    class AppDelegate: NSObject, UIApplicationDelegate {
        
        func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
                // Override point for customization after application launch.
                let configuration = Configuration(writeKey: "1234567890")
                    .trackApplicationLifecycleEvents(true)
                    .flushInterval(10)

                analytics = Analytics(configuration: configuration)
                analytics.add(plugin: UIKitScreenTracking())
                #error:  Value of optional type 'Analytics?' must be unwrapped to refer to member 'add' of wrapped base type 'Analytics'
            
            return true
        }
    }
