### ISSUE TITLE
XCFramework is missing macOS Slices

### ISSUE THREAD

**Issue by arielelkin** [segmentio/analytics-swift#207]
The xcframeworks available in https://github.com/segmentio/analytics-swift/releases only contain iOS slices even though this project is compatible with macOS and watchOS.

**Comment by arielelkin** [comment]
@bsneed any updates?

**Comment by bsneed** [comment]
I confirmed the issue, but haven't had time to get to a fix/PR for it yet.

**Comment by arielelkin** [comment]
@bsneed could we have an ETA on this? It looks like it's mostly a matter of adding one line of xcodebuild here: https://github.com/segmentio/analytics-swift/blob/main/build.sh#L38

**Comment by bsneed** [comment]
Fixed!  Thanks for your patience @arielelkin
