### ISSUE TITLE
Segment 1.4.0 issue with AppsFlyer

### ISSUE THREAD

**Issue by jhpassion0621** [segmentio/analytics-swift#211]
I updated segment to 1.4.0, latest version but I have build issue on appsflyer.
![Screenshot 2023-03-29 at 10 12 07 PM](https://user-images.githubusercontent.com/7741402/228566159-a0485c6f-5de9-48bb-8d98-a220e81726bb.png)

**Comment by xmollv** [comment]
We're having a similar issue, looks like `1.4.0` changed the API signature.

**Comment by skydivedan** [comment]
I cannot build with 1.4.0 at all right now, because of this. I simply created a sample app, then added in Optimizely's-segment package, and got identical results.

**Comment by bsneed** [comment]
Working on a fix for this; should be out shortly.

**Comment by bsneed** [comment]
Fixed in 1.4.1 and 1.4.2.  You'll probably need to update the apps flyer integration as well if using objc.
