### ISSUE TITLE
Library evolution error "No such module Sovran" when using the xcframework

### ISSUE THREAD

**Issue by blbnv** [segmentio/analytics-swift#213]
I am trying to use`Segment` by using an attached `xcframework`. After adding a framework, importing it into my host application and just building I have a problem with (I suppose) the library evolution of `Sovran` (the framework Segment depends on).

The error violation for the `import Semgent`
```
Failed to build module 'Segment' for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug
```

The error violation into `swiftinterface` file:
```
No such module 'Sovran'
```

**To Reproduce**

* Xcode 14.2 (14C18)
* Segment 1.4.0 [release](https://github.com/segmentio/analytics-swift/releases/tag/1.4.0)

1. Create an empty application with iOS 16.0 as a minimum deployment target
2. Download an `xcframework` from the [release 1.4.0](https://github.com/segmentio/analytics-swift/releases/tag/1.4.0)
3. Drag and drop `xcframework` into a newly created application
4. Make sure the `Embed and sign` option is selected for a given framework since it's a dynamic one. If this step will be not done, the dynamic library will fail to load at runtime.
5. Make `import Segment` in any of the application files
6. Build the project

**Expected behavior**
Build succeeded.

**Actual Behaviour**
Build failed.

**Screenshots**
<img width="476" alt="Screenshot 2023-04-07 at 11 56 16" src="https://user-images.githubusercontent.com/8416769/230588728-6741632b-4f84-4d73-8eee-f9c8b9c9e00c.png">

<img width="1011" alt="Screenshot 2023-04-07 at 11 56 55" src="https://user-images.githubusercontent.com/8416769/230588818-feabb363-acc5-48b0-8bac-1e0627b32901.png">

**Platform (please complete the following information):**
 - Library Version in use: 1.4.0
 - Platform being tested: iOS, Xcode 14.2 14C18
 - Integrations in use: N/A

**Additional context**
I suppose it's because of the swift library evolution. All modules that the framework depends on should be built with library evolution and the internal usage of them should be marked with `@_implementationOnly import Sovran`.

**Comment by bsneed** [comment]
Working on this along with #207

**Comment by bsneed** [comment]
Fixed!  Implementationonly wouldn't suffice as it leaves out any protocol imports.  Pull the xcframework for Sovran (which is on the release page at that repo now) and you should be good.
