### ISSUE TITLE
Automatic Push notification tracking

### ISSUE THREAD

**Issue by aiden-whatnot** [segmentio/analytics-swift#217]
I saw there's a automatic push notification tracking available [here](https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#automatic-push-notification-tracking) but didn't see an implementation for swift. Is there any plan to add this in?

<img width="713" alt="Screen Shot 2023-04-17 at 11 58 03 AM" src="https://user-images.githubusercontent.com/104326213/232584733-33d19c65-2a47-429b-8984-204997c1f060.png">

**Comment by bsneed** [comment]
See here: https://github.com/segmentio/analytics-swift/blob/main/Examples/other_plugins/NotificationTracking.swift

It was a portion of the analytics-ios SDK that customers regularly wanted to customize so we externalized it for maximum flexibility.
