### ISSUE TITLE
Usage document link in Readme.md dead 

### ISSUE THREAD

**Issue by HaibinWangAe** [segmentio/analytics-swift#218]
**Describe the bug**
In Readme.md, the usage documentation link to https://segment.com/docs/connections/sources/catalog/libraries/mobile/swift-ios/ points to a url that doesn't exist. 

**To Reproduce**
1. Visit https://github.com/segmentio/analytics-swift
2. Click on the usage documentation link under Documentation section 
3. 404 Error -- The page you were looking for doesn't exist.

**Expected behavior**
Show the right documentation

**Comment by bsneed** [comment]
Thanks!  Fixed it.
