### ISSUE TITLE
runtime error when integrating Segment xcframework: “Segment.framework” is damaged and can’t be opened. You should move it to the Bin. 

### ISSUE THREAD

**Issue by arielelkin** [segmentio/analytics-swift#223]
Trying to integrate [the Segment xcframework](https://github.com/segmentio/analytics-swift/releases/tag/1.4.3) into a macos app. The project builds successfully but produces this error at runtime:

![image](https://user-images.githubusercontent.com/1756909/235902095-d2478ec5-2096-4405-8dbf-c6dde06f9ef7.png)

Here's a very small demo project reproducing the issue:
https://github.com/arielelkin/segment-xcframework-bug

Note that it produces the following build warnings: 
![image](https://user-images.githubusercontent.com/1756909/235902048-983f83a9-3759-4fee-89f3-5b3e629c650e.png)

**Comment by alanjcharles** [comment]
Hi @arielelkin I cloned your example app and I am unable to reproduce this issue (see screenshot). The app builds as expected for me. Is there any other information you can provide or context I might be missing? I would also recommend reaching out to `friends@segment.com` for a faster, more in-depth troubleshooting experience. They will also be able to escalate any potential bugs to us. Thanks! 
<img width="906" alt="image" src="https://github.com/segmentio/analytics-swift/assets/50601149/0c9704cb-e640-4a48-81a4-a9e8a5fd0a83">

**Comment by arielelkin** [comment]
In our experience this error is often caused by the user's Gatekeeper or System Integrity Protection not trusting the app and its components. This would explain why it happens on your machine but not ours. Often due to codesigning issues.

Is the xcframework being codesigned at all?

Is there another machine (that doesn't have your code signing certificate installed) that you can try running the sample project on?

**Comment by bsneed** [comment]
You should sign the framework yourself.  You'd have to re-sign it anyway to ship your app, so there's no sense in code signing on our end.  See https://stackoverflow.com/questions/30963294/creating-ios-osx-frameworks-is-it-necessary-to-codesign-them-before-distributin
