### ISSUE TITLE
Incorrect OS version reported to Amplitude

### ISSUE THREAD

**Issue by zachwaugh** [segmentio/analytics-swift#228]
**Describe the bug**
I'm in the process of upgrading our apps from `analytics-ios` to `analytics-swift`. After the upgrade, Segment is now reporting the operating system to Amplitude ("OS" property) as "Webkit 605" where previously it would be correctly reported as "ios 16.4.1". This is going to mess up our tracking of installed OS versions going forward.

Sorry if this is the incorrect place to report this, but it didn't happen with the previous library and it happens with this one, so I assume the problem is here but realize it may be a server issue in how the data is processed.

**To Reproduce**
1. Integrate this library
2. Track some events
3. Observe that the OS value is incorrect

**Expected behavior**
I expect the operating system to be reported correctly

**Screenshots**

Before (analytics-ios)
<img width="645" alt="Screenshot 2023-05-18 at 4 38 39 PM" src="https://github.com/segmentio/analytics-swift/assets/21447/085a2a7f-bd4c-463c-97da-bcbe2de8cffa">

After(analytics-swift)
<img width="645" alt="Screenshot 2023-05-18 at 4 27 44 PM" src="https://github.com/segmentio/analytics-swift/assets/21447/c731b854-4446-4bc6-9077-fb3f78672879">

**Platform (please complete the following information):**
 - Library Version in use: 1.4.5
 - Platform being tested: iOS, macOS
 - Integrations in use: Amplitude

**Comment by alanjcharles** [comment]
@zachwaugh  just to confirm- are you using amplitude in Cloud Mode or Device Mode (have the amplitude package included in your app)?

**Comment by zachwaugh** [comment]
@alanjcharles  We're using Amplitude in Cloud mode, only analytics related package we have is Segment.

**Comment by alanjcharles** [comment]
thanks @zachwaugh 

so I tried to recreate your issue. Here's what I did

1. set up an `Amplitude Actions` Cloud Mode Destination (with no custom mappings) 
![image](https://github.com/segmentio/analytics-swift/assets/50601149/a02f0bc3-015e-47d0-a792-77824372c3cc)

2. sent events from swift to segment and confirmed OS is correct
![image](https://github.com/segmentio/analytics-swift/assets/50601149/eb993a99-e26b-4da8-96a5-36136be902e8)

3.. check amplitude instance and see it's setting platform correctly
![image](https://github.com/segmentio/analytics-swift/assets/50601149/cdc47769-e46f-47cb-b6ce-580dfe9a0be7)

As you can see everything is mapped as we would expect. If you are using the `Amplitude Actions` destination I would recommend checking any mappings you have. Please let me know if you are using the `Amplitude Classic` destination and I will attempt to escalate the issue with the appropriate team. We can safely say that the `Analytics Swift` library is working as expected. Let me know what you think and we can go from there. Thanks!

**Comment by zachwaugh** [comment]
I appreciate you looking into this @alanjcharles! I *think* we're on Amplitude Classic, but I didn't originally set this up and I don't see anyway in the UI to determine if it's Classic or Actions. Let me know if I'm missing something on where to look for that info. But if Classic is deprecated and Actions is recommended and doesn't have this bug, I can look into updating our configuration.

<img width="389" alt="Screenshot 2023-05-19 at 1 43 15 PM" src="https://github.com/segmentio/analytics-swift/assets/21447/c2be0ecb-e1a7-4d58-8184-1f2569bc956e">

**Comment by alanjcharles** [comment]
no problem @zachwaugh! I believe you are using the classic destination. It's not deprecated, just in maintenance mode. So, if this is a bug, it's likely something they will take on. Regardless, I would recommend updating to the actions destination since it is likely that support for the classic destination will be quite limited moving forward. 

If you want to get updates on the progress of this bug, I would recommend reaching out to `friends@segment.com` and just let them know you would like regular status updates. You can send them a link to this conversation to make things simpler. Let me know if there is anything else I can do to help!

**Comment by zachwaugh** [comment]
Thanks again! I'll close this since it's not an issue in the library itself.
