### ISSUE TITLE
App hanging when accessing userAgent value

### ISSUE THREAD

**Issue by everuribe** [segmentio/analytics-swift#229]
**Describe the bug**
Since we started tracking app not responding instances, we have seen that many of our users experience app hanging of more than 10 seconds when `AppleUtils.userAgent` is accessed, specifically
```
WKWebView().value(forKey: "userAgent") as? String
```

This happens when analytics is configured (app launch). 

**To Reproduce**
Not consistently reproducible. 

**Expected behavior**
Perhaps this value could be set asynchronously, not in main thread, once it is available (unless this value must be accessed on main...). Or the option to not include this property could be provided. 

**Screenshots**
<img width="1496" alt="image" src="https://github.com/segmentio/analytics-swift/assets/47759786/108d3ec1-716e-4a48-b50d-d936ab849bc0">

**Platform (please complete the following information):**
 - Library Version in use: 1.4.0
 - Platform being tested: macOS

**Comment by bsneed** [comment]
That's really weird, thanks for pointing it out!  I'm sure we can lazy fill it somehow.  I'll swing back to this with a PR in a bit.

**Comment by bsneed** [comment]
Fixed!  A couple more issues to look at and then a release.

**Comment by bsneed** [comment]
Fixed in 1.4.6
