### ISSUE TITLE
Support Cocoapods

### ISSUE THREAD

**Issue by renatomcit** [segmentio/analytics-swift#231]
**Is your feature request related to a problem? Please describe.**
Do you have an idea if this library will support Cocoapods?

**Describe the solution you'd like**
I'm using this library as a dependency of an SDK which only supports Cocoapods for now, and I'm not able to use it as SPM

**Describe alternatives you've considered**
I was thinking if I could create the podspec and the just relates to your code, or use the framework to deliver as a pod, but I believe if it comes from you will be better

**Comment by dmcgloin** [comment]
Please don't support CocoaPods

**Comment by bsneed** [comment]
We're not going to support Cocoapods.  If you absolutely need it, you can make a fork and add a pod spec as shown here: https://github.com/xiaodoudou/analytics-swift/commit/6c3d24e7dfb2b1ce12e86a4f381be6e33e94a70f
