### ISSUE TITLE
WriteKey Exposure in document directory

### ISSUE THREAD

**Issue by Yinzo** [segmentio/analytics-swift#232]
**Describe the bug**
My SwiftUI app for iOS  turns on "Supports Document Browser" in plist, which expose the document directory to Files app in iOS. And I found the  segment directory is located in the document directory, which use the WriteKey as sub-folder name.

This might cause the WriteKey exposed incidentally

**To Reproduce**
 1. turns on "Supports Document Browser" in plist
 2. In 'Files' App, locate to My iPhone > [app name] > segment
 3. You can see some folders, naming with the WriteKey

I only tested on iOS 16.4

**Expected behavior**
segment event cache might not be located in document directory, maybe Application Support or Cache diretory like tvOS

**Screenshots**

**Platform (please complete the following information):**
 - Library Version in use:   __segment_version = "1.3.5" 
 - Platform being tested: iOS 16.4
 - Integrations in use: [e.g. Firebase, Amplitude]

**Additional context**

**Comment by bsneed** [comment]
Writekey is not intended to be private.
