### ISSUE TITLE
Question: Is it safe to create more than one `Analytics` object with different `configuration`?

### ISSUE THREAD

**Issue by dmcgloin** [segmentio/analytics-swift#235]
Wanting to know if it's OK to create two instances of the main Analytics class in a single application. I understand this is not recommended, but is it supported? We have case where we need to send some events to a separate pipeline.

Thanks for listening.

**Comment by bsneed** [comment]
@dmcgloin yup!  You can see an example here: https://github.com/segmentio/analytics-swift/blob/main/Examples/tasks/MultiInstance.swift
