### ISSUE TITLE
RequestFacotry configuration method desn't work

### ISSUE THREAD

**Issue by HyenaJeremyLin** [segmentio/analytics-swift#239]
**Describe the bug**
I replaced old library analytics-ios to analytics-swift in my project, and set the requestFactory configuration in new library analytics-swift, the requestFactory configuration work in analytics-ios, but it doesn't work in analytics-swift, is there something wrong with my configuration?

**To Reproduce**
In the old library analytics-ios requestFactory configuration work
```swift
let configuration = AnalyticsConfiguration(writeKey: segmnetIOKey)
configuration.trackApplicationLifecycleEvents = true
configuration.recordScreenViews = false
configuration.trackPushNotifications = true
configuration.maxQueueSize = 10000
configuration.requestFactory = { url in
          if let components = NSURLComponents(url: url, resolvingAgainstBaseURL: false) {
                components.host = segmentIOHost
                if let transformedURL = components.url {
                    return NSMutableURLRequest(url: transformedURL)
                }
            }
            return NSMutableURLRequest(url: url)
        }
Analytics.setup(with: configuration)

```

In the new library analytics-swift requestFactory configuration doesn't work
```swift
let configuration = Configuration(writeKey: segmnetIOKey)
            .trackApplicationLifecycleEvents(true)
            .requestFactory { url in
                if var components = URLComponents(url: url.url!, resolvingAgainstBaseURL: false) {
                    components.host = segmentIOHost
                    if let transformedURL = components.url {
                        return try! URLRequest(url: transformedURL, method: .put)
                    }
                }
                return url
            }
            .errorHandler { error in
                print("Analytics configuration error[\(error)]")
            }
        analytics = Analytics(configuration: configuration)
        analytics.add(plugin: AmplitudeSession())
```

**Platform (please complete the following information):**
 - analytics-ios 4.1.6, analytics-swift 1.4.6
 - iOS sdk 13.0
 - Integrations in use: Amplitude

**Comment by bsneed** [comment]
Looks like it's working to me.  You may have to debug it there a little to see since I can't reproduce it.  Please reopen this ticket if necessary.

<img width="743" alt="image" src="https://github.com/segmentio/analytics-swift/assets/235787/a63f28c4-ed98-4980-82dd-e9a4fe35d240">

**Comment by HyenaJeremyLin** [comment]
Hi @bsneed 
What wrong with configuration error handler response 'networkServerRejected' after set the apiHost.

![截圖 2023-07-03 上午9 32 23](https://github.com/segmentio/analytics-swift/assets/59005776/fb9b1bd3-5c63-4b15-9723-f6fec0cb8ac1)

**Comment by bsneed** [comment]
Because the server is rejecting your request.  Something is wrong with your URL.  Revisit your requestFactory implementation according to whatever specs and debug it.  It's not a library issue.
