### ISSUE TITLE
issues integrating xcframework ("Failed to build module 'Segment' for importation due to the errors above; the textual interface may be broken by project issues or a compiler bug")

### ISSUE THREAD

**Issue by arielelkin** [segmentio/analytics-swift#241]
I'm trying to integrate the Segment and Sovran xcframeworks from release v1.4.7, but have been build errors. Please see the small demo project below to reproduce the issue:
 https://github.com/arielelkin/segment-xcframework-bug-2/tree/master

![image](https://github.com/segmentio/analytics-swift/assets/1756909/c3828c48-c2ba-4e70-9535-ef0d7523704a)

You'll see that in the swift package manifest I've defined Sovran as a dependency of Segment, but it seems like it still can't resolve it. I've integrated xcframeworks like this in the past, so I'm not sure if it's because of a bug in SPM or in how Segment imports Sovran. 

In any case, it'd be useful to either offer a separate SPM package with the xcframeworks, or add xcframework integration instructions to this repo's README.

**Comment by bsneed** [comment]
I can't tell what you're doing there, BUT, I tested it with the sample project to sent to us previously and it works as expected best I can tell.  Drop the frameworks into the root there and you should see it build appropriately.
[HosterFive.zip](https://github.com/segmentio/analytics-swift/files/12004327/HosterFive.zip)
