### ISSUE TITLE
How to specify event version

### ISSUE THREAD

**Issue by nickruddeni** [segmentio/analytics-swift#242]
How should we specify a specific event version to validate against when tracking events as specified here https://segment.com/docs/protocols/tracking-plan/create/#:~:text=Tracking%20Plan%20Event-,Versioning,-Segment%20offers%20Tracking

Previously we'd add the context object via the `options` parameter to trackEvent calls. That has now been removed.

**Comment by bsneed** [comment]
You'd do this via `analytics.add(enrichment: { ... return modifiedEvent })`
