### ISSUE TITLE
Question: Difference between docs and Github for using segment with watchOS

### ISSUE THREAD

**Issue by cprince-foreflight** [segmentio/analytics-swift#250]
On the docs in https://segment-docs.netlify.app/docs/connections/sources/catalog/libraries/mobile/ios/, it says: 

> Segment does not currently support tracking of watchkit extensions for the Apple Watch. [Email us](https://segment.com/requests/integrations/) if you’re interested in a Watchkit SDK. For now we recommend tracking watch interactions using the iPhone app code.

However, on your main page About you say:

> The hassle-free way to add Segment analytics to your Swift app (iOS/tvOS/watchOS/macOS/Linux).

Is WatchOS supported for use with Segment analytics?

**Comment by lalmalani** [comment]
[Analytics-Swift](https://github.com/segmentio/analytics-swift) supports WatchKit. The previous iteration of the library, Analytics-iOS does not.
