### ISSUE TITLE
Pass anonymousId in Segment identify API in swift version

### ISSUE THREAD

**Issue by Vidyaranigrao** [segmentio/analytics-swift#251]
Using Segment Objective-C version we were passing anonymousId in the <options> parameter of identify API. After migrating to swift version we are no longer able to do that. As per the documentation it says we can pass the anonymousId at the same level as userId but we are getting error while trying to do so. 

**To Reproduce**
Analytics.main.identify(
            anonymousId: "Anonymous Id",
            userId: "UserId",
            traits: "Traits Dictionary"
        )

Error : Extra argument 'anonymousId' in call

**Platform (please complete the following information):**
 - Segment 1.4.5
 - Platform being tested: iOS
 - Integrations in use: Amplitude

**Comment by bsneed** [comment]
If you could point me to that documentation you're referring to, I can go fix it.  The options parameter has been removed.  You can write a small plugin to set anonymousId on events as you see fit.
