### ISSUE TITLE
Argument passed to call that takes no arguments

### ISSUE THREAD

**Issue by alexanderPayClip** [segmentio/analytics-swift#260]
**Describe the bug**
xCode send this error "Argument passed to call that takes no arguments" after configure in `didFinishLaunchingWithOptions `

```
private let WRITE_KEY = "xxxxxxxxxx"
    
    var analytics: Analytics? = nil
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        let configuration = Configuration(writeKey: WRITE_KEY)
            .trackApplicationLifecycleEvents(true)
            .flushInterval(10)
            .flushAt(2)
        
        analytics = Analytics(configuration: configuration)
        
        return true
    }
```

**Comment by bsneed** [comment]
Can you share a screenshot of what you're seeing in Xcode?

**Comment by alexanderPayClip** [comment]
Just that:
<img width="674" alt="Captura de pantalla 2023-10-25 a la(s) 11 52 03" src="https://github.com/segmentio/analytics-swift/assets/98480959/97c1103a-79ad-4004-a0ab-ef5dc596f138">

on line:
analytics = Analytics(configuration: configuration)

**Comment by bsneed** [comment]
More context would be helpful, but if you can't provide it i understand.  You can look in the source and see easily that configuration is the argument that needs to be passed.  Check to see if you’re having a class name conflict and it thinks it’s talking to something it’s not.
