### ISSUE TITLE
Event files can contain corrupted JSON data

### ISSUE THREAD

**Issue by NicFontana** [segmentio/analytics-swift#266]
**Describe the bug**
Event files, used to store events data to be uploaded, can contain corrupted data.

**To Reproduce**
I don't know if there is a way to reproduce this, but from what we can see in our server logs, we are sometimes receiving corrupted JSON files from our users.
(We are using the request factory configuration to redirect every request the SDK does to our own servers).

**Expected behavior**
The uploaded event files should contain valid JSON.

**Platform:**
 - Library Version in use: 1.4.5
 - Platform being tested: iOS

**Additional context**
Looking at the iOS simulator app's directories, I've been able to locate a couple of corrupted files (`0-segment-events.temp` and `2-segment-events.temp`) and by opening them I can see that each file contains the file ending string defined in `Storage.swift`:
```swift
// write it to the existing file
let fileEnding = "],\"sentAt\":\"\(sentAt)\",\"writeKey\":\"\(writeKey)\"}"
```
but after that line, more content has been written.

Attached a couple of screenshots of the files content.

`0-segment-events.temp`
<img width="494" alt="0" src="https://github.com/segmentio/analytics-swift/assets/23361963/1ee71d87-304d-4f5d-8c8d-733b55d47d90">

`2-segment-events.temp`
<img width="1322" alt="2" src="https://github.com/segmentio/analytics-swift/assets/23361963/ce1d8d7b-cf30-4446-b4aa-2dff2ebc2162">

**Comment by bsneed** [comment]
Hi @NicFontana, i'm unable to reproduce this, or really even see how this could happen in code.  There's also the fact it's going through your pass through server that makes it difficult for me to do much with this.  Please reopen if you have a reproduction outside of your environment.
