### ISSUE TITLE
Why does Segment have an encoding error for Foundation.Date objects?

### ISSUE THREAD

**Issue by goodones-mac** [segmentio/analytics-swift#278]
**Describe the bug**
I'm trying to track an event with `Foundation.Date` objects inside of them, which are Codable and are seemingly getting translated into strings internally.  This causes issues with your custom JSON encoder.  What is going on?

**Screenshots**
<img width="1830" alt="Screenshot 2023-11-27 at 1 41 46 PM" src="https://github.com/segmentio/analytics-swift/assets/123040996/654d9acb-fd1d-4d3b-809a-a1a7166aa0ed">
<img width="1828" alt="Screenshot 2023-11-27 at 1 37 17 PM" src="https://github.com/segmentio/analytics-swift/assets/123040996/2906b72c-ecfe-4ce1-bcaa-68beefff6182">

**Platform (please complete the following information):**
 - Library Version in use: 1.4.8
 - Platform being tested: iOS
 - Integrations in use: None

**Additional context**
We are evaluating migrating from direct mixpanel tracking, thus the mixpanel types.

**Comment by bsneed** [comment]
Have a look at the `main` branch.  This might have been addressed already via #273.  If that doesn't take care of it, please reopen this ticket.  A release will be made shortly containing this fix.
