### ISSUE TITLE
Temporary Files Get Stored In User's Documents Directory On Windows

### ISSUE THREAD

**Issue by brianmichel** [segmentio/analytics-swift#283]
**Describe the bug**
When using this SDK on Windows, the temporary files are written to a user's `Documents` directory. This feels like the wrong place for these documents since they are really temp files and could be purged without much issue. I feel like these should probably be somewhere in `AppData` for packaged applications, and somewhere in `temp` otherwise.

This is doubly weird on more modern Windows installs because your user directory is sync'd across machines using OneDrive. So these are going to potentially get copied to other Windows machines that I'm signed into.

**To Reproduce**
1. Run the test suite
2. Observe the folder on disk

**Expected behavior**
I should not see segment information in my documents directory.

**Screenshots**
![image](https://github.com/segmentio/analytics-swift/assets/63919/e54b1196-4830-42c3-92ad-dfbd684943de)

**Platform (please complete the following information):**
 - Library Version in use: 1.4.8
 - Platform being tested: Windows (although this problem is likely the same on Linux)
 - Integrations in use: n/a

**Additional context**

**Comment by bsneed** [comment]
I agree.  I think the same is true for Mac/linux as well.  I've got some storage changes coming up and was planning on making this a configuration option, along with some defaults per-platform.  Let me know if you have suggestions for any of the platforms your team supports.

**Comment by bsneed** [comment]
Should be fixed now.
