### ISSUE TITLE
Nit: Allow date formatting to be configured by client?

### ISSUE THREAD

**Issue by cprince-foreflight** [segmentio/analytics-swift#284]
**Is your feature request related to a problem? Please describe.**
This is more of a nit than anything else, but it would be nice. Our app currently does date formatting using the `ISO8601DateFormatter()` configured with `formatter.formatOptions.insert(.withFractionalSeconds)`. In this way, we get a string date with a format like:
"2023-10-04T21:41:12.000Z"

The default date formatter in Segment currently formats dates slightly differently. For example:
"2023-12-13T23:26:37.091+0000"

**Describe the solution you'd like**
Could date formatting be configurable by the calling client? E.g., through supplying a `DateEncodingStrategy` for the JSONEncoder and `DateDecodingStrategy` for the JSONDecoder?

**Comment by bsneed** [comment]
Hi @cprince-foreflight, yeah, definitely, it's a possibility!  Though, we don't want to go that route probably as we need consistent dates across the board.  Last I looked, we were getting the 000Z version you show but it has been a minute since I checked.  Segment internally needs 8601 dates universally, so the options provided by JSONDecoder are more than would be desirable.  If you have an idea and PR, I can probably get it merged pretty quick if it follows the 000Z format.  Otherwise, it'll likely be post holidays.

**Comment by cprince-foreflight** [comment]
Looking at this more this morning, I'm realizing that the date formatting difference I'm finding has to do with using the Codable interface versus the non-Codable interface in Segment 1.5.0.

[_Codable interface_](https://github.com/segmentio/analytics-swift/blob/266c374bd9c55a3101e0b5f04a9f8cab4eee747a/Sources/Segment/Events.swift#L17)
Default date formatting:
"2023-12-13T23:26:37.091+0000"

[_non-Codable interface_](https://github.com/segmentio/analytics-swift/blob/266c374bd9c55a3101e0b5f04a9f8cab4eee747a/Sources/Segment/Events.swift#L145)
Default date formatting:
"2023-12-14T16:03:14.300Z"

Looking for the underlying difference in the code now.

**Comment by cprince-foreflight** [comment]
I see it now. Different date formatters are being used:

_Codable_
[Code reference](https://github.com/segmentio/analytics-swift/blob/266c374bd9c55a3101e0b5f04a9f8cab4eee747a/Sources/Segment/Utilities/JSON.swift#L22)
```
extension DateFormatter {
    static let iso8601: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
        formatter.calendar = Calendar(identifier: .iso8601)
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        formatter.locale = Locale(identifier: "en_US_POSIX")
        return formatter
    }()
}
```

_Non-Codable_
[Code reference](https://github.com/segmentio/analytics-swift/blob/266c374bd9c55a3101e0b5f04a9f8cab4eee747a/Sources/Segment/Utilities/iso8601.swift#L21)
```
    enum SegmentISO8601DateFormatter {
    static let shared: ISO8601DateFormatter = {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions.update(with: .withFractionalSeconds)
        return formatter
    }()
```

Looking into a PR to fix now.

**Comment by bsneed** [comment]
Thanks @cprince-foreflight !  Nice work, very clean!  Will do a release once the gh actions finish up on main.
