### ISSUE TITLE
Notification observer is not being called "io.segment.analytics.integration.did.start"

### ISSUE THREAD

**Issue by asadkazmi-mset** [segmentio/analytics-swift#288]
**Describe the bug**
I updated my segment analytics to the swift version from Obj-c using SPM.
After updating I cannot find 'SEGAnalyticsIntegrationDidStart' in the scope, so after some research I found I should be using this string literal "io.segment.analytics.integration.did.start"
But after using that my observer function is not being called, previously before migration it was called with this "SEGAnalyticsIntegrationDidStart" notification
```
notificationCenter.addObserver(self,
                                       selector: #selector(integrationDidStart(_:)),
                                       name: NSNotification.Name(rawValue: "io.segment.analytics.integration.did.start"),
                                       object: nil)
```

**To Reproduce**
use the "io.segment.analytics.integration.did.start" as an observer and its callback will not be called as it suppose to be called

**Expected behavior**
This selector function(integrationDidStart()) should call if I have added the observer("io.segment.analytics.integration.did.start") correctly.

**Platform (please complete the following information):**
 - Library Version in use: 1.5.1
 - Platform being tested: iOS
 - Integrations in use: Segment analytics with desitination firebase, adjust, braze

**Comment by bsneed** [comment]
Hi @asadkazmi-mset, that observer is part of analytics-ios, not analytics-swift.  You can probably do something like this ...

```
DispatchQueue.someQueue.async {
    analytics.waitUntilStarted()
    // do something now that it has.
}
```
