### ISSUE TITLE
SEGIntegration and SEGIntegrationFactory

### ISSUE THREAD

**Issue by benMohamed** [segmentio/analytics-swift#309]
Does Segment Swift have an equivalent for SEGIntegrationFactory and SEGIntegration? Is it the same as DestinationPlugin?

**Comment by alanjcharles** [comment]
Hi @benMohamed- yep. `DestinationPlugin` is equivalent to `SEGIntegrationFactory` and `SegmentDestination` is  equivalent to `SEGIntegration`. Hope this helps! Please feel free to reach out to `friends@segment.com` for faster response times and more detailed answers.

**Comment by benMohamed** [comment]
@alanjcharles  thank you so much
