### ISSUE TITLE
Build fails: `isUnitTesting` only available in DEBUG mode

### ISSUE THREAD

**Issue by collinhundley** [segmentio/analytics-swift#312]
In AppleUtils.swift, line 253:
```
if isUnitTesting == false {
```

`isUnitTesting` is defined in Utils.swift, but only in DEBUG mode. So, the build fails for all non-debug builds.

Bug introduced in v1.5.6
Platform: macOS

**Comment by bsneed** [comment]
Thanks for spotting that @collinhundley !  Ugh, userAgent has been the bane of my existence lately. :(   I'll get this fixed in just a minute and do another release.

**Comment by collinhundley** [comment]
@bsneed thanks!
