### ISSUE TITLE
Question: Is it supported multiple instance write key?

### ISSUE THREAD

**Issue by guiihlopes** [segmentio/analytics-swift#316]
Hi, I would like to know if it's supported multiple instances with **different write keys**.

Currently I'm working in a single project application which has multiple contexts. Some of these contexts should send informations to worskpace1 and others to workspace2. And I couldn't find in the docs what the best practice should be to deal with this situation.

The only information I've found about this topic is in a confused way, because there's two different information in each side:

![image](https://github.com/segmentio/analytics-kotlin/assets/14032146/7ccb7b07-b5b5-41aa-bb84-ff0e0d803e69)
Source: https://segment.com/docs/connections/sources/catalog/libraries/mobile/apple/

![image](https://github.com/segmentio/analytics-kotlin/assets/14032146/91210291-6b8f-4453-bfb8-d1c85a509f21)
Source: https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/ios-faqs/

**How could I handle this scenario which I need to split the sent informations based in a context?**

**Comment by alanjcharles** [comment]
@guiihlopes yep, definitely. See the example here: https://github.com/segmentio/analytics-swift/blob/main/Examples/tasks/MultiInstance.swift. Please feel free to reach out to `friends@segment.com` for additional troubleshooting help and more detailed answers to implementation questions. Hope this helps!
