### ISSUE TITLE
Adding a plugin to Analytics causes a circular reference

### ISSUE THREAD

**Issue by kmpa** [segmentio/analytics-swift#326]
It seems that when an Amplitude plugin is added to Analytics using `.add(plugin:) `method it will cause a circular reference to Analytics.

This becomes a problem in our application as we need to be able free all services that are used in the application. Now because of the circular reference the application will crash, starting from the version 1.5.3 onwards. This version introduced a check in Analytics init method for multiple instances having the same write key.

In case no plugins are added there is no circular reference and Analytics can be freed normally.

Operating system: iOS
Reproduced: Every time

**Comment by bsneed** [comment]
Looks like an issue with the amplitude plugin not marking the analytics var as weak.  Will address it over there.  Thanks for finding that @kmpa!

**Comment by bsneed** [comment]
See https://github.com/segment-integrations/analytics-swift-amplitude/releases/tag/1.3.2

**Comment by sergiymomot** [comment]
@bsneed same for https://github.com/segment-integrations/analytics-swift-appsflyer

**Comment by bsneed** [comment]
Thanks @sergiymomot !  I'll go get that one updated.

**Comment by bsneed** [comment]
done!

**Comment by sergiymomot** [comment]
@bsneed thanks for the quick fix 💯
