### ISSUE TITLE
Rename of `JSONSafeEncoder` -> `JSONSafeEncoding` has broken previous releases

### ISSUE THREAD

**Issue by tiltem** [segmentio/analytics-swift#332]
**Describe the bug**
Rename of `JSONSafeEncoder` -> `JSONSafeEncoding` has broken previous releases.

**To Reproduce**
Use release before 1.5.10. These releases will get most recent `JSONSafeEncoding` since the package defined `from: 1.0.0`. The code and package for these releases reference `JSONSafeEncoder` so package resolution fails, and build would fail on imports with the old name. Seems `JSONSafeEncoding` rename should be released as 2.0.0

**Comment by bsneed** [comment]
Hi @tiltem, it didn't seem like there were any good options given the actual repo changed (other than dupe the repo).  There's probably not much to do at this point outside of upgrade.  In the meantime, I think you should able to pin a specific version in your app and that will propagate to the analytics-swift package since it's open ended.  What do you think?

**Comment by harrywombat** [comment]
```
xcodebuild: error: Could not resolve package dependencies:
Dependencies could not be resolved because 'analytics-swift' >= 1.5.6 contains incompatible tools version (5.9.0) and root depends on 'analytics-swift' 1.5.10..<[REDACTED].0.0.
```

I'm getting this issue when I try to build on Bitrise since upgrading to 1.5.10, and also cannot roll back as stated above either.

I'm not sure which 'tools version (5.9.0)' it's referring to because JSONSafeEncoding and Sovran are in the 1.0.0 range.

Any ideas?

**Comment by tristan-warner-smith** [comment]
Is this referring to the Xcode tools version specified in the Package.swift? Swift 5.9 comes with Xcode 15.0.

**Comment by bsneed** [comment]
I just pulled 1.5.10 and JSONSafeEncoding 1.0.2 (moved to 2.0).  Will release analytics-swift 1.5.11 shortly.

"tools-version" is referring to the Swift version (5.9.0), not your project or dependencies.
