### ISSUE TITLE
What's happened to 1.5.10?

### ISSUE THREAD

**Issue by malcommac** [segmentio/analytics-swift#336]
We have implemented this release in our production app but today we have seen it was removed without any notice from the repository.
What's wrong with this release? Should be worried and publish a new update reverting to 1.5.9 (or .11 or whatever?!). Btw this is a weird behavior and we're a little worried about that since it's not the first time is happened from the far I can remember.

**Comment by bsneed** [comment]
We've never had to pull a release before.  

Unfortunately, I messed up with the rename for a dependency by not marking it 2.0, but rather 1.0.2.  This had the unintentional consequence of users of previous versions to begin pulling in an incompatible dependency.  I didn't have many good options, and pulling a release that had only been out for a few days seemed like the best option and least painful for the majority of customers.  My apologies for the hassle associated.
