### ISSUE TITLE
iOSLifecycleEvents.application(didFinishLaunchingWithOptions:) is Compiled for More than 400 ms

### ISSUE THREAD

**Issue by art-divin** [segmentio/analytics-swift#339]
**Describe the bug**

Segment SDK is distributed as a source via SPM.
Upon compilation, a single method `func application(_ application: UIApplication?, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?)` takes irrationally long time for compiling.

**To Reproduce**
1. Compile `iOSLifecycleEvents.swift` with the following flags:
```swift
for target in package.targets {
target.swiftSettings = target.swiftSettings ?? []
target.swiftSettings?.append(
  .unsafeFlags([
   "-Xfrontend", "-warn-long-function-bodies=30", "-Xfrontend", "-warn-long-expression-type-checking=30"
  ])
)
}
```
2. Observe Xcode warnings

**Expected behavior**
There should be no longer than usual 0.3 - 0.5 ms of compiling `iOSLifecycleEvents.application(didFinishLaunchingWithOptions:)` on M1 family SoC.

**Screenshots**
<img width="30%" alt="image" src="https://github.com/segmentio/analytics-swift/assets/1614869/92aaa67f-b593-46d6-ab05-d1b2a459e386">

**Platform (please complete the following information):**
 - Library Version in use: 1.5.5
 - Platform being tested: macOS
 - Integrations in use: N/A

**Additional context**
Using https://github.com/qonto/SwiftCompilationTimingParser it is easier to address such issues, but the approach described with Xcode also works.

**Comment by bsneed** [comment]
Please submit a PR if you'd like to see this changed.  The things in there are typed already, urls, strings, etc.  It's a basic dictionary.

**Comment by art-divin** [comment]
Hello @bsneed , PR is submitted linking against this issue. Thank you ⚡️🔥🔥🔥

**Comment by bsneed** [comment]
Right on!  I totally missed it.
