### ISSUE TITLE
Modify some context from Plugin

### ISSUE THREAD

**Issue by miquelalvarado** [segmentio/analytics-swift#346]
**Describe the bug**
We need to anonymize the last byte of the IP when certain conditions are met. For that we have an Enrichment Plugin that tries to get the `ip` key from the context and map it but it doesn't seem to be there by that point.

**To Reproduce**
1. Create an Enrichment Plugin
2. Try to get the ip value from any event context
3. It will return nil

**Expected behavior**
IP is already accessible.

**Platform (please complete the following information):**
 - Library Version in use: 1.5.11
 - Platform being tested: iOS

**Additional context**
My guess is that certain context attributes are added internally by another Plugin at a later stage. Ideally I think that when our Plugins are executed the event should be as real as possible (meaning having the same elements that will be sent in the final event and before processing clients' plugins).
Maybe there's another kind of Plugin (not enrichment) that could fit this need?

**Comment by bsneed** [comment]
The `ip` value in context is set server side.  If you supply your own `ip` address, the server won't add that value.  However, the value the server sets would be inaccessible on-device.  You can do what you're requesting via Segment's Functions product ([here](https://segment.com/docs/connections/functions/))
