### ISSUE TITLE
Crash at "specialized iOSVendorSystem.deviceModel()"

### ISSUE THREAD

**Issue by sergiymomot** [segmentio/analytics-swift#349]
**Describe the bug**
Crashes reported in Firebase Crashlytics: 
"specialized iOSVendorSystem.deviceModel(), EXC_BREAKPOINT"

**To Reproduce**
It's not easily reproducible, but it happens on many iOS versions before iOS 16 (12, 13, 14, 15).
Seems to happen at the app start during Segment SDK initialization (stack traces file attached below).

**Platform (please complete the following information):**
 - Library Version in use: 1.5.11
 - Platform being tested: iOS
 - Integrations in use: AppsFlyer

**Additional context**
Stack traces: [com.current.currentapp_issue_ac90c3dd14c06ab345dbdb30cc4073c0_crash_session_557172359d5e4cc99cac687b6c89e5a9_DNE_0_v2_stacktrace.txt](https://github.com/segmentio/analytics-swift/files/15338355/com.current.currentapp_issue_ac90c3dd14c06ab345dbdb30cc4073c0_crash_session_557172359d5e4cc99cac687b6c89e5a9_DNE_0_v2_stacktrace.txt)

**Comment by bsneed** [comment]
Thanks @sergiymomot!  That's very peculiar.  I just modified it to use the same mechanism as macOS.  Not sure why/how they ended up differently.  I verified the output is identical as well.  A release with this should be coming tomorrow.
