### ISSUE TITLE
Failure to generate xcframework

### ISSUE THREAD

**Issue by breno-unspun** [segmentio/analytics-swift#357]
**Describe the bug**
The command `./build.sh` is crashing

**To Reproduce**

1. install mint
2. install unsignedapps/swift-create-xcframework
3. run ./build.sh

output:
```
Removing old files ...
Building XCFrameworks ...
warning: unable to restore workspace state: unknown 'WorkspaceStateStorage' version '6' at '***/analytics-swift/.build/workspace-state.json'
debug: evaluating manifest for 'analytics-swift' v. unknown
error: missingKey("product_type")
debug: evaluating manifest for 'analytics-swift' v. unknown
error: missingKey("product_type")
Error: fatalError
Done.
```

**Platform:**
 - Library Version in use: 1.5.11
 - Platform being tested: iOS
 - Integrations in use: -

**Additional context**
I had change the swift-tools-version in the package.swift file to 5.7. 
Before making this change I was getting the following error: 
```
Removing old files ...
Building XCFrameworks ...
warning: unable to restore workspace state: unknown 'WorkspaceStateStorage' version '6' at '***/analytics-swift/.build/workspace-state.json'
error: package 'analytics-swift' is using Swift tools version 5.9.0 but the installed version is 5.7.0
error: package 'analytics-swift' is using Swift tools version 5.9.0 but the installed version is 5.7.0
Error: fatalError
Done.
```

Installed versions:
```
$ swift --version
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

$ which swift
/usr/bin/swift

$ mint --version
Version: 0.17.5

$ swift create-xcframework --version
2.3.0
```

**Comment by bsneed** [comment]
use the package here instead of the mint-based one.  https://github.com/segment-integrations/swift-create-xcframework

I'll update this script the future.  it wasn't expected that customers use that script since xcframeworks are uploaded as part of the release.
