### ISSUE TITLE
Seeing vastly more "Application installed" events since upgrading from 1.5.9 to 1.6.0

### ISSUE THREAD

**Issue by danniss10** [segmentio/analytics-swift#364]
**Describe the bug**
We recently upgraded our analytics-swift version from 1.5.9 to 1.6.0. Since doing so, we have seen our volume of daily Application Installed events (from the application lifecycle events in the library) nearly double, while our other custom events have stayed roughly the same.

We are struggling to understand what to make of this. We are wondering if there is some change in the library that is more efficiently sending the application installed events now?

We are also noticing after looking further into the data that huge volumes of these users have already downloaded and used our app and are having Application Installed called again.

**To Reproduce**

This is our configuration 
```
        let segmentKey = getSegmentKey()
        let configuration = Configuration(writeKey: segmentKey)
            .trackApplicationLifecycleEvents(true)
        

        analytics = Analytics(configuration: configuration)
```

**Expected behavior**

Holding all else constant, we expect the relative volume of application lifecycle events to be mostly constant relative to similar following custom events such as our custom `splash screen viewed` event. 

**Platform (please complete the following information):**
 - Library Version in use: 1.6.0
 - Platform being tested: iOS
 - Integrations in use: Amplitude

**Additional context**

We have always noticed that the number of Application Installed events from segment were lower than the number seen on App Store Connect. We always assumed that this was just because many people download and don't open the app. Now over the last few days we are actually see volumes of Application Installed events that are sometimes _higher_ then shown on App Store Connect. In theory, these two numbers should mostly align we think. 

Really appreciate help in understanding these discrepancies!

**Comment by bsneed** [comment]
Hi @danniss10!  Are you using any device mode destinations like amplitude?  Also, it looks like this fix came in recently.  https://github.com/segmentio/analytics-swift/commit/be284887a23b83bd10538635653d42c8b6c3a15f but hasn't been released yet.  It looks/sounds like it could address what you're talking about.  Can you have a look and share your thoughts?

**Comment by danniss10** [comment]
Thanks for the quick response @bsneed!

We aren't doing anything special with amplitude in the SDK/at a code level. I think it's just one of our normal destinations in the web UI.

With respect to the fix you mentioned, that does look like it's addressing the issue we are facing! Do you know when it will be released/is there a way to leverage the fix now?

Also noticed the fix is in one of the plugins -- is there something special I have to do to use the plugin or does `.trackApplicationLifecycleEvents(true)` automatically default to using that plugin?

**Comment by bsneed** [comment]
I can do a release now for you.  Give me just a moment and 1.6.1 will be up.  No, nothing special you need to do.  It's one of the auto-loaded plugins, so it should "just work".

**Comment by bsneed** [comment]
Done!  Thanks so much @danniss10 !

**Comment by danniss10** [comment]
Huge, thank you for the quick turnaround @bsneed!!

**Comment by bsneed** [comment]
Thanks to @remstos for the fix!  :high-five:
