### ISSUE TITLE
defined(__OBJC__) returning false 

### ISSUE THREAD

**Issue by SweatSzemis** [segmentio/analytics-swift#368]
**Describe the bug**
I'm attempting to use the latest Segment Swift Packing in my Objective C project,
I've added it my project using Swift package Manager.

In the Segment-Swift.h file going straight to the unsupported Swift architecture error.
Any guidance would be appreciated.

```
#if defined(__OBJC__)
OBJECTIVE-C CODE
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
```

**Expected behavior**
Able to import  Segment successfully

`@import Segment;
`
**Screenshots*
<img width="930" alt="Screenshot 2024-10-09 at 4 13 19 pm" src="https://github.com/user-attachments/assets/736d59db-193f-4b8f-aad4-8f551ff2d8ea">
*

**Platform (please complete the following information):**
 - Library Version in use: 1.6.2
 - Platform being tested: [e.g. iOS]

**Comment by bsneed** [comment]
Have you tried the Objc Example here?  https://github.com/segmentio/analytics-swift/tree/main/Examples/apps/ObjCExample

It builds and seems to work fine.  Seems likely something maybe in your project setup? Lemme know if this works for you.

**Comment by SweatSzemis** [comment]
Thank you for the response. I figured the issue is most likely a project setup issue. However I am having trouble nailing it down. Do you have any suggestion about what to look for potentially.

**Comment by bsneed** [comment]
My apologies @SweatSzemis, I missed your response.  You've likely solved it by now, if so I'm curious what the issue was.  I didn't really have any guesses on my end.

**Comment by bsneed** [comment]
If you're still having issues, feel free to reopen this ticket.

**Comment by SweatSzemis** [comment]
I've found that the project will compile on a test device. So this has unblocked our progress.
However, in simulator the unsupported Swift architecture error occurs so until resolved we can't use the simulator anymore.
