### ISSUE TITLE
Updating to analytics-swift version 1.6.2 causes build error in LivePlugins file when built along with analytics-swift-filters library

### ISSUE THREAD

**Issue by seanperez29** [segmentio/analytics-swift#370]
**Describe the bug**
I have both this analytics-swift library and analytics-swift-filters library, and whenever I update this one to the latest version (1.6.2) I get a build error in the LivePlugins file stating "Cannot assign to property: 'loaded' is a get-only property".

**To Reproduce**
1. Have DestinationFilters-Swift (analytics-swift-filters) version 0.1.1 and analytics-swift version 1.5.11 and attempt to update analytics swift to 1.6.2
2. Build project and error occurs

**Screenshots**
<img width="1289" alt="384182313-4c6130a8-dd1e-4ce7-9e32-b69059bf4ff3" src="https://github.com/user-attachments/assets/31c4714f-fac2-467c-a215-3a671cf702fb">

**Platform (please complete the following information):**
 - Library Version in use: Currently on 1.5.11, but am trying to update to 1.6.2
 - Platform being tested: iOS, Xcode version 15.4
 - Integrations in use: DestinationFilters-Swift

**Comment by bsneed** [comment]
We've got changes coming for this shortly; currently waiting on some internal stuff to get finalized.

**Comment by seanperez29** [comment]
Sweet sounds good, thanks!

**Comment by bsneed** [comment]
Hi @seanperez29 please move to this version: https://github.com/segment-integrations/analytics-swift-live/releases/tag/3.1.0

Code changes should be minimal (if any).  As licensing changed and we move closer to GM with live/filters/signals, it was necessary that we remove all prior versions.  I apologize in advance for any broken builds in the meantime.

**Comment by seanperez29** [comment]
Worked great! Thanks!
