### ISSUE TITLE
New crash on 1.7.1 related to Telemetry (reports from Crashlytics)

### ISSUE THREAD

**Issue by lluisgerard** [segmentio/analytics-swift#375]
**Describe the bug**
The issue was clear with 1.7.0 because it happened right when you opened the app. 
With version 1.7.1 it may not happen often but I receive reports from Crashlytics.

**To Reproduce**
I don't know how to reproduce, I get crashlytics reports.

**Expected behavior**
Not crash

**Screenshots**
```
          Crashed: com.apple.NSURLSession-delegate
0  FieldMargin                    0xcb388c specialized Telemetry.error(metric:log:buildTags:) + 169 (Telemetry.swift:169)
1  FieldMargin                    0xc574a0 Analytics.reportInternalError(_:fatal:) + 76 (Errors.swift:76)
2  FieldMargin                    0xca092c specialized HTTPClient.handleResponse(data:response:error:url:completion:) + 101 (HTTPClient.swift:101)
3  FieldMargin                    0xc9f994 closure #1 in HTTPClient.startBatchUpload(writeKey:batch:completion:) + 4379916692
4  FieldMargin                    0xca0c58 partial apply for closure #1 in HTTPClient.startBatchUpload(writeKey:batch:completion:) + 4379921496
5  FieldMargin                    0x2ccf90 thunk for @escaping @callee_guaranteed @Sendable (@guaranteed Data?, @guaranteed NSURLResponse?, @guaranteed Error?) -> () + 4369616784 (<compiler-generated>:4369616784)
6  CFNetwork                      0xadd60 CFHostCreateCopy + 13544
7  CFNetwork                      0xadb40 CFHostCreateCopy + 13000
8  libdispatch.dylib              0x213c _dispatch_call_block_and_release + 32
9  libdispatch.dylib              0x3dd4 _dispatch_client_callout + 20
10 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain + 748
11 libdispatch.dylib              0xbf64 _dispatch_lane_invoke + 432
12 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh + 288
13 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread + 404
14 libsystem_pthread.dylib        0x4934 _pthread_wqthread + 288
15 libsystem_pthread.dylib        0x10cc start_wqthread + 8
        
```

**Platform (please complete the following information):**
 - Library Version in use: 1.7.1
 - Platform being tested: Reports from iOS 17.5.1 (iPhone 15) and iOS 18.0.0 (iPhone 14) with recurring crashes.
 - Integrations in use: Amplitude

**Additional context**
Crash already reported on 1.7.0 that was supposed to be fixed (it was for me when opening the app) but it seems to happen in some yet unknown conditions. Previous reports on 1.7.0 https://github.com/segmentio/analytics-swift/issues/371 https://github.com/segmentio/analytics-swift/issues/373

**Comment by MichaelGHSeg** [comment]
Thank you for the report, I'm looking into the issue.

**Comment by lluisgerard** [comment]
> Thank you for the report, I'm looking into the issue.

Thanks! Let me know if you need any more information. As of now I see 10 crashes affecting 5 users (according to Crashlytics reports).

**Comment by lluisgerard** [comment]
@MichaelGHSeg Thanks for looking at this. As we get more people into our latest release we see more reported crashes that are highly concentrated to the same users. So far I could not see a specific trait that could help.

Do you think it could be possible to downgrade to version 1.6.2? could that cause any other issues? Thanks

**Comment by MichaelGHSeg** [comment]
There shouldn't be any issue with downgrading.  There hopefully should be a fix out soon as well.

**Comment by MichaelGHSeg** [comment]
1.7.2 is out and should fix the issue.  Thanks you for the help!

**Comment by lluisgerard** [comment]
@MichaelGHSeg Thanks! I will update asap 👍
