### ISSUE TITLE
Setting trackApplicationLifecycleEvents to false strips context

### ISSUE THREAD

**Issue by tcldr** [segmentio/analytics-swift#41]
Hi,

I've noticed that if `trackApplicationLifecycleEvents` is set to false, the context is stripped from all events.

I imagine this line should sit before the conditional block:

https://github.com/segmentio/analytics-swift/blob/ebdd751f1a04030c78ff4bdc787e0519f6bfe21f/Sources/Segment/Startup.swift#L44

One other thing: I would actually like to use application lifecycle events but I prefer a different naming scheme. Is there someway to set this manually? Thanks!

**Comment by bsneed** [comment]
Thanks @tcldr, I'll look into this ASAP!

**Comment by tcldr** [comment]
@bsneed my pleasure.

**Comment by tcldr** [comment]
Really liking this library. So lightweight compared to most other analytics dependencies!

**Comment by bsneed** [comment]
Also found that on macOS, the correct VendorSystem class isn't getting returned.  Doh!!  Fixing that too.
