### ISSUE TITLE
Data loss after quick successive calls to `flush()`

### ISSUE THREAD

**Issue by tcldr** [segmentio/analytics-swift#48]
**Describe the bug**
Assuming the Segment debugger is showing all events, I've noticed that certain event are frequently lost when there are multiple calls to flush in a row.

**To Reproduce**
Add the following to your `sceneDidBecomeActive(_:)` or similar:
```
for i in 0..<10 {
    analytics.track(name: "rapid event \(i)")
    analytics.flush()
}
```

**Expected behavior**
Events 0-9 appearing in Segment's source debugger.

**Actual behavior**
*Most* events arrive but... missing one or two here and there!

**Screenshots**
<img width="658" alt="Screenshot 2021-08-21 at 13 48 33" src="https://user-images.githubusercontent.com/26437279/130322296-e553ae18-a1d4-4e8d-8a50-82728be21954.png">
*Here we're missing 2 and 8*

**Platform (please complete the following information):**
 - Library Version in use: master
 - Platform being tested: iOS latest
 - Integrations in use: None

**Additional context**
 - Lifecycle events are OFF
 - `flush()` called regularly at key events

**Comment by bsneed** [comment]
Looking ...

**Comment by bsneed** [comment]
Hi @tcldr, I verified what you're seeing here, but all events are being sent out.  See this bit in the segment documentation:

https://segment.com/docs/connections/sources/debugger/

```
The Debugger is separate from your workspace's data pipeline and is not an exhaustive view of all the events ever sent to your Segment workspace. The Debugger only shows a sample of the events that the Source receives in real time, with a cap of 500 events. The Debugger is a great way to test specific parts of your implementation to validate that events are being fired successfully and arriving to your Source.
```

^ that was news to me as well, but it is accurate and no events are being lost.  The flushing in quick succession is what's causing the debugger to not sample some parts of the event stream.

**Comment by tcldr** [comment]
Good to know. Thanks for taking a look!
