### ISSUE TITLE
track(event:properties:) takes [String:Any], but screen(screenTitle:properties:) takes [Any:Hashable]

### ISSUE THREAD

**Issue by JetForMe** [segmentio/analytics-swift#51]
**Describe the bug**
There's a bit of mismatch/asymmetry between the various `track` and `screen` methods. Namely, `track(event:properties:)` takes `[String:Any]`, but `screen(screenTitle:properties:)` takes [Any:Hashable]`.

**Expected behavior**
I'd expect these to take the same thing, unless there's some reason they can't.

**Platform (please complete the following information):**
 - Library Version in use: 1.0.2
 - Platform being tested: [e.g. iOS]

**Comment by bsneed** [comment]
Good find!  Will post the change shortly.
