### ISSUE TITLE
Docs for identify(userID:traits:) say to pass nil for userID, but it's non-optional

### ISSUE THREAD

**Issue by JetForMe** [segmentio/analytics-swift#58]
**Describe the bug**
The header docs for `identify(userID:traits:)` say to pass `nil` for `userID` if you don’t have a user ID, but it's a non-optional String.

I need to be able to clear the identified user if the user logs out of our app.

**Comment by tcldr** [comment]
Yeah, I need this too – for the period where a user ID hasn't been retrieved yet. In the mean time, I'd like to add traits to an anonymous user.

**Comment by bsneed** [comment]
> **Describe the bug** The header docs for `identify(userID:traits:)` say to pass `nil` for `userID` if you don’t have a user ID, but it's a non-optional String.

This is an error in the documentation, and I'll correct that.

> 
> I need to be able to clear the identified user if the user logs out of our app.

If a user logs out of the app, you should call analytics.reset();  I'll make this documentation change/clarification as well.

**Comment by bsneed** [comment]
> Yeah, I need this too – for the period where a user ID hasn't been retrieved yet. In the mean time, I'd like to add traits to an anonymous user.

You should call `identify(traits: )` in this case.
