### ISSUE TITLE
Drop SPM watchOS min version to 6.0

### ISSUE THREAD

**Issue by dannyhertz** [segmentio/analytics-swift#61]
**Is your feature request related to a problem? Please describe.**
We need to support watchOS 6.0 for our app and would really like to this this SDK.

**Describe the solution you'd like**
Drop the min supported watchOS version from 7.1 to 6.0

**Describe alternatives you've considered**
Not using this SDK

**Additional context**
Since you already support iOS 13 and I can't seem to find any used APIs that would prevent 6.0, perhaps this is a much easier change than you think!

**Comment by bsneed** [comment]
Hi @dannyhertz,

Thanks for inquiring about this.  Unfortunately we can't do that.  Lifecycle tracking would be severely effected in doing so, namely that it'd have to be done completely differently.  If you clone it and set it to 6.0, you can see the errors and incompatibilities pop up.

**Comment by dannyhertz** [comment]
Ah, okay. Thanks for the explanation and fast response!

**Comment by bsneed** [comment]
No problem @dannyhertz!  Sorry I couldn't make that happen for you. :(
