### ISSUE TITLE
Main Thread Checker: UI API called on a background thread: -[UIView init]

### ISSUE THREAD

**Issue by Jeehut** [segmentio/analytics-swift#69]
**Describe the bug**
Calling `Analytics.init()` crashes my app with the following error:
```
Main Thread Checker: UI API called on a background thread: -[UIView init]
```

The line causing the crash is this in `AppleUtils.swift`s `userAgent` computed property:
```swift
return WKWebView().value(forKey: "userAgent") as? String
```

**To Reproduce**
1. Call the initializer of `Analytics` from a background thread (e.g. `utility`)

**Expected behavior**
Analytics is a task that I expect to work in the background.

**Screenshots**

**Platform (please complete the following information):**
 - Library Version in use: 1.0.3
 - Platform being tested: iOS 15
 - Integrations in use: N/A

**Additional context**
N/A

**Comment by bsneed** [comment]
Thanks @Jeehut !
