### ISSUE TITLE
Compile error in Release configuration archiving with 1.0.4

### ISSUE THREAD

**Issue by JetForMe** [segmentio/analytics-swift#89]
**Describe the bug**
The following compile-time errors occur in Segment 1.0.4 when archiving a `Release` configuration app:

```
…/SourcePackages/checkouts/analytics-swift/Sources/Segment/Utilities/JSON.swift:305:19: error: thrown expression type 'String' does not conform to 'Error'
            throw "This JSON object is not an array type."
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
…/SourcePackages/checkouts/analytics-swift/Sources/Segment/Utilities/JSON.swift:328:19: error: thrown expression type 'String' does not conform to 'Error'
            throw "This JSON object is not an array type."
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
…/SourcePackages/checkouts/analytics-swift/Sources/Segment/Utilities/JSON.swift:350:19: error: thrown expression type 'String' does not conform to 'Error'
            throw "This JSON object is not an array type."
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm not sure why it works in `Debug` configuration builds, but it seems odd to be throwing a `String`. I tried searching but couldn't find an `Error` conformance for `String` in the package.

**Comment by oscar-tome** [comment]
Any chance this will be resolved promptly? It's currently blocking us from adopting the framework.

**Comment by JetForMe** [comment]
I reverted to 1.0.3 to be able to build, but I'd really like to see this fixed so I can suppress all the extra logging in 1.0.3.

**Comment by bsneed** [comment]
@oscar-tome @JetForMe looking into it now.  one moment.

**Comment by bsneed** [comment]
Resolved in 1.0.5.

Thanks for reporting this!  Looks like it's been there for a bit.  Issue was actually in something Sovran-Swift was exporting.

**Comment by JetForMe** [comment]
Works great! Somehow we were also throwing strings in our own code (not code I wrote 😆), and had even added our own protocol conformance on `String` to `Error` for release builds. This is much better.

**Comment by oscar-tome** [comment]
Closing the circle here: build works and adoption is continuing at the planned pace. We're starting to see reporting show up in the servers and, having had experience with several analytics tracking frameworks, I'd say that this one's on the better side of things.

**Comment by bsneed** [comment]
Hi @oscar-tome We appreciate that feedback very much!  Thank you!
