### ISSUE TITLE
Where did all the releases go?

### ISSUE THREAD

**Issue by davisg123** [segmentio/analytics-swift#97]
Github is only listing the latest release 1.0.6 now... was that intentional?

```Dependencies could not be resolved because no versions of 'analytics-swift' match the requirement 1.0.5 and root depends on 'analytics-swift' 1.0.5.```

https://github.com/segmentio/analytics-swift/releases

**Comment by bsneed** [comment]
Holy moly, it was NOT intentional.  Ugh.  I just updated my gh util via brew, I wonder if that's what did it.  I've run this script many times now and that's never happened and it hasn't changed. :(

**Comment by bsneed** [comment]
Will report back once I understand what happened.  In the meantime, I'll add 1.0.5 back (albeit without release notes.  Ugh)

**Comment by bsneed** [comment]
Nevermind, it deleted all the tags too. <sigh>

**Comment by bsneed** [comment]
I republished the tags from my local and everything is showing up again.  If it disappears again, I'll do the same.  I've gotta test the gh tool to see if that's what's causing it so it may likely happen again.
